from __future__ import annotations

import hashlib
import collections
import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts/build_stage12689_source_backed_maintenance_history_corpus.py"


def load_module():
    spec = importlib.util.spec_from_file_location("stage12689", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def git(repo: Path, *args: str, env: dict[str, str] | None = None, check: bool = True) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args], check=check, text=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env,
    )
    return result.stdout.strip()


def commit(repo: Path, message: str, index: int) -> str:
    env = dict(os.environ)
    env.update({
        "GIT_AUTHOR_DATE": f"2021-02-{index + 1:02d}T00:00:00Z",
        "GIT_COMMITTER_DATE": f"2021-02-{index + 1:02d}T00:00:00Z",
    })
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", message, env=env)
    return git(repo, "rev-parse", "HEAD")


def create_repo(root: Path, index: int, *, secret: bool = False, generated: bool = False, patch_value: int | None = None) -> Path:
    repo = root / f"repo-{index:03d}"
    repo.mkdir()
    git(repo, "init", "-q")
    git(repo, "config", "user.email", "fixture@example.invalid")
    git(repo, "config", "user.name", "Fixture")
    git(repo, "remote", "add", "origin", f"https://example.invalid/repo-{index:03d}.git")
    source = repo / "module.py"
    replacement = index + 2 if patch_value is None else patch_value
    source.write_text(
        f"# fixture repository {index}\ndef compute(value):\n    return value + 1\n",
        encoding="utf-8",
    )
    commit(repo, "Initial verified implementation", 0)
    if generated:
        source.write_text(
            f"# This file is automatically generated\n# fixture repository {index}\ndef compute(value):\n    return value + {replacement}\n",
            encoding="utf-8",
        )
    elif secret:
        source.write_text(
            f"# fixture repository {index}\ndef compute(value):\n    token = 'AKIA1234567890ABCDEF'\n    return value + {replacement}\n",
            encoding="utf-8",
        )
    else:
        source.write_text(
            f"# fixture repository {index}\ndef compute(value):\n    adjusted = value + {replacement}\n    return adjusted\n",
            encoding="utf-8",
        )
    commit(repo, f"Preserve adjusted return behavior for repository {index}\n\nRecord a verified child revision.", 1)
    return repo


def fixture_split(module, repo: Path) -> str:
    revision = git(repo, "rev-parse", "HEAD")
    origin = git(repo, "config", "--get", "remote.origin.url")
    repo_key = module.stable([origin, revision])
    component_key = module.stable([repo_key])
    bucket = int(component_key[:8], 16) % 20
    return "train" if bucket < 16 else "eval" if bucket < 18 else "strict_eval"


def populate_split_supply(
    root: Path,
    module,
    requirements: dict[str, int],
    *,
    start_index: int = 1000,
) -> dict[str, list[Path]]:
    pool = root.parent / f"{root.name}-candidate-pool"
    pool.mkdir()
    selected = {split: [] for split in requirements}
    index = start_index
    while any(len(selected[split]) < count for split, count in requirements.items()):
        repo = create_repo(pool, index)
        split = fixture_split(module, repo)
        if split in requirements and len(selected[split]) < requirements[split]:
            destination = root / f"{split}-{len(selected[split]):03d}"
            repo.rename(destination)
            selected[split].append(destination)
        index += 1
        if index - start_index > 1000:
            raise AssertionError("unable to construct deterministic split fixture")
    return selected


def test_object_commit_path_and_content_rejections(tmp_path: Path) -> None:
    module = load_module()
    data = b"verified object\n"
    oid = hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()
    assert module.verify_object_oid(oid, "blob", data)
    assert not module.verify_object_oid("0" * 40, "blob", data)
    identities = module.parse_ls_tree_object_identities(
        b"040000 tree " + b"1" * 40 + b"\tvendor\0"
        + b"100644 blob " + b"2" * 40 + b"\tvendor/generated.min.js\0"
        + b"100644 blob " + b"3" * 40 + b"\thuge.bin\0"
        + b"160000 commit " + b"4" * 40 + b"\tsubmodule\0"
    )
    assert set(identities) == {
        ("tree", "1" * 40),
        ("blob", "2" * 40),
        ("blob", "3" * 40),
        ("commit", "4" * 40),
    }
    assert module.path_allowed("src/module.py")
    assert not module.path_allowed("vendor/module.py")
    assert not module.path_allowed("dist/bundle.js")
    assert not module.path_allowed("src//module.py")
    assert not module.path_allowed("src/module.py/")
    assert not module.path_allowed("src/control\x1f.py")
    assert module.safe_text_blob(b"ordinary source\n") == "ordinary source\n"
    assert module.safe_text_blob(b"version https://git-lfs.github.com/spec/v1\noid sha256:x\n") is None
    assert module.safe_text_blob(b"binary\x00content") is None
    assert module.safe_text_blob(b"token=AKIA1234567890ABCDEF") is None
    assert module.safe_text_blob(b"# This file is automatically generated\nvalue = 1\n") is None

    with pytest.raises(module.Stage12689Error, match="root_or_merge_commit"):
        module.parse_commit(b"tree " + b"1" * 40 + b"\n\nroot message\n")
    with pytest.raises(module.Stage12689Error, match="not_one_modified_file"):
        module.parse_single_path_change(b"A\0new.py\0")
    with pytest.raises(module.Stage12689Error, match="not_one_modified_file"):
        module.parse_single_path_change(b"M\0one.py\0M\0two.py\0")


@pytest.mark.parametrize("message", [
    "token=sk-proj-12345678901234567890",
    "Contact maintainer@example.com about repair",
    "Signed-off-by: Maintainer <maintainer@example.com>",
    "Co-authored-by: Helper <helper@example.com>",
    "Reviewed-by: Reviewer <reviewer@example.com>",
    "Acked-by: Reviewer <reviewer@example.com>",
    "Change-Id: I0123456789abcdef",
    "dependabot updates a pinned dependency",
    "renovate[bot] refreshes dependency versions",
    "Merge branch main into release",
    "Revert parser boundary repair",
    "Update files",
    "Misc changes",
    "Bump version",
    "Bump dependencies to current versions",
    "WIP",
    "chore: cleanup parser",
    "chore(deps): refresh package pins",
    "WIP: repair parser boundary later",
    "Code cleanup",
    "Fix parser",
])
def test_maintenance_subject_rejects_secrets_identity_trailers_and_bots(message: str) -> None:
    module = load_module()
    assert module.message_span(message + "\n", "unrelated exact diff") is None


@pytest.mark.parametrize("body", [
    "token=sk-proj-12345678901234567890",
    "Contact maintainer@example.com before release",
    "Signed-off-by: Maintainer",
    "Co-authored-by: Helper",
    "Reviewed-by: Reviewer",
    "Acked-by: Reviewer",
    "Change-Id: I0123456789abcdef",
    "Generated by dependabot",
    "Automated by release bot",
    "credential_url=https://user:password@example.invalid/private",
    "Authorization: Bearer abc.def.ghi",
    "private_key rotation details",
    "token rotation details",
    "password rotation details",
    "secret rotation details",
    "Opened by github-actions",
    "Prepared by release-please",
    "Security update from snyk automation",
    "Generated with copilot",
])
def test_full_commit_message_contamination_rejects_clean_subject(body: str) -> None:
    module = load_module()
    message = f"Repair parser boundary handling safely\n\n{body}\n"
    assert module.message_span(message, "unrelated exact diff") is None


def test_maintenance_target_is_clean_subject_only() -> None:
    module = load_module()
    subject = "Repair parser boundary handling safely"
    message = subject + "\n\nExplain the verified behavior in detail.\n"
    evidence = "changed_file: src/parser.py\n- parser boundary\n+ parser boundary handling"
    assert module.message_span(message, evidence) == (0, len(subject))
    assert module.message_span(
        message + "Signed-off-by: Person <person@example.com>\n", "unrelated exact diff",
    ) is None


@pytest.mark.parametrize("subject", [
    "Repair module behavior safely today",
    "Improve repository code quality safely",
    "Fix maintenance issue behavior correctly",
    "Repair parent child transition safely",
    "Adjusted return semantics remain consistent",
])
def test_subject_requires_action_and_specific_changed_identifier(subject: str) -> None:
    module = load_module()
    evidence = "changed_file: module.py\n- return value\n+ adjusted = value\n+ return adjusted"
    assert module.message_span(subject + "\n", evidence) is None


def test_subject_preserves_exact_source_text_when_linked() -> None:
    module = load_module()
    subject = "Repair adjusted return handling safely"
    evidence = "changed_file: module.py\n- return value\n+ adjusted = value\n+ return adjusted"
    span = module.message_span(subject + "\n", evidence)
    assert span == (0, len(subject))
    assert (subject + "\n")[span[0]:span[1]] == subject


def test_capacity_estimator_preserves_cross_component_patch_dedup(tmp_path: Path) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    create_repo(root, 41, patch_value=7)
    create_repo(root, 42, patch_value=7)
    snapshots, counters = module.discover_repositories(root, 10)
    module.assign_components(snapshots)
    assert len({snapshot.component_key for snapshot in snapshots}) == 2
    capacities = module.estimate_component_row_capacities(snapshots, counters)
    assert sum(capacities.values()) == 2
    assert len(capacities) == 1


def test_capacity_allocator_handles_uneven_whole_components(tmp_path: Path) -> None:
    module = load_module()

    def snapshot(repo_suffix: str, component_key: str):
        return module.Snapshot(
            tmp_path / repo_suffix, repo_suffix * 64,
            f"https://example.invalid/{repo_suffix}.git", "1" * 40, [],
            (), (), component_key=component_key,
        )

    capacities = {"a": 13, "b": 7, "c": 3, "d": 2, "e": 1}
    snapshots = [
        snapshot("a", "a"), snapshot("a2", "a"), snapshot("b", "b"),
        snapshot("c", "c"), snapshot("d", "d"), snapshot("e", "e"),
    ]
    assignments = module.allocate_components_by_capacity(
        snapshots, capacities, {"train": 16, "eval": 2, "strict_eval": 2},
    )
    assigned_capacity = {split: 0 for split in ("train", "eval", "strict_eval")}
    for component_key, capacity in capacities.items():
        assigned_capacity[assignments[component_key]] += capacity
    assert assigned_capacity["train"] >= 16
    assert assigned_capacity["eval"] >= 2
    assert assigned_capacity["strict_eval"] >= 2
    assert snapshots[0].split == snapshots[1].split


def test_default_500_is_proven_under_worst_inventory_skew(tmp_path: Path) -> None:
    module = load_module()
    assert module.MAX_ROWS == 500
    assert module.DEFAULT_CAPACITY_EVIDENCE == {
        "accepted_repositories": 525,
        "largest_component_capacity": 6_430,
        "positive_capacity_components": 53,
        "total_buildable_rows": 7_202,
    }
    capacities = {"largest": 6_430, "remainder-large": 721}
    capacities.update({f"unit-{index:02d}": 1 for index in range(51)})
    assert len(capacities) == 53
    assert sum(capacities.values()) == 7_202
    assignments = module.allocate_components_by_capacity(
        [], capacities, {"train": 400, "eval": 50, "strict_eval": 50},
    )
    assigned_capacity = collections.Counter()
    for component_key, capacity in capacities.items():
        assigned_capacity[assignments[component_key]] += capacity
    assert assigned_capacity["train"] >= 400
    assert assigned_capacity["eval"] >= 50
    assert assigned_capacity["strict_eval"] >= 50


def test_capacity_allocator_fails_closed_for_indivisible_supply(tmp_path: Path) -> None:
    module = load_module()
    snapshots = [
        module.Snapshot(tmp_path / "a", "a" * 64, "https://example.invalid/a.git",
                        "1" * 40, [], (), (), component_key="a"),
        module.Snapshot(tmp_path / "b", "b" * 64, "https://example.invalid/b.git",
                        "2" * 40, [], (), (), component_key="b"),
    ]
    with pytest.raises(module.Stage12689Error) as captured:
        module.allocate_components_by_capacity(
            snapshots, {"a": 9, "b": 1},
            {"train": 8, "eval": 1, "strict_eval": 1},
        )
    assert str(captured.value) == "requested_split_caps_unfilled"
    assert all(snapshot.split == "" for snapshot in snapshots)


def test_source_proof_rows_reconstruct_and_ignore_target_mutation(tmp_path: Path) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    repo = create_repo(root, 1)
    revision = git(repo, "rev-parse", "HEAD")
    change = module.read_change(repo, revision)
    snapshot = module.Snapshot(
        local_path=repo, repo_key="a" * 64,
        origin_url="https://example.invalid/repo.git", revision=revision,
        changes=[change], lineage_keys=("root:x",), component_objects=(),
        component_key="b" * 64, split="train",
    )
    maintenance = module.build_maintenance_row(snapshot, change)
    diff = module.build_small_diff_row(snapshot, change)
    assert maintenance is not None and diff is not None
    for row, proof in (maintenance, diff):
        target = row["target"]["decoder_text"]
        assert row["input_text"].count(module.MASK) == 1
        assert target not in row["input_text"]
        assert module.normalized(target) not in module.normalized(row["input_text"])
        assert proof["exact_reconstruction_verified"] is True
        mutated = json.loads(json.dumps(row))
        mutated["target"]["decoder_text"] = "a completely different target"
        assert mutated["input_text"] == row["input_text"]
        assert all(value is False for value in row["authority"].values())
    assert maintenance[0]["objective_family"] == "maintenance_commit_message_span_completion"
    assert "Record a verified child revision." not in maintenance[0]["input_text"]
    assert "<COMMIT_MESSAGE>" not in maintenance[0]["input_text"]
    assert maintenance[0]["source_provenance"]["message_body_rendered"] is False
    assert diff[0]["objective_family"] == "small_diff_exact_child_hunk_completion"
    assert change.parent_blob_oid != change.child_blob_oid


def test_trainer_renderer_isolated_from_target_and_provenance_mutation(tmp_path: Path) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    repo = create_repo(root, 7)
    revision = git(repo, "rev-parse", "HEAD")
    change = module.read_change(repo, revision)
    snapshot = module.Snapshot(
        local_path=repo, repo_key="a" * 64,
        origin_url="https://example.invalid/repo.git", revision=revision,
        changes=[change], lineage_keys=("root:x",), component_objects=(),
        component_key="b" * 64, split="train",
    )
    built = module.build_maintenance_row(snapshot, change)
    assert built is not None
    row, _proof = built
    mutated = json.loads(json.dumps(row))
    mutated["target"]["decoder_text"] = "FORGED TARGET MUST NOT ENTER ENCODER"
    mutated["source_provenance"] = {
        "target": "FORGED PROVENANCE MUST NOT ENTER ENCODER",
        "positive_chunk_ids": ["oracle"],
    }

    training_data_path = ROOT / "legacy_src/agentkernel_lite/training_data.py"
    spec = importlib.util.spec_from_file_location("stage12689_training_data", training_data_path)
    assert spec and spec.loader
    training_data = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = training_data
    spec.loader.exec_module(training_data)

    rendered = training_data._row_text(row)
    mutated_rendered = training_data._row_text(mutated)
    assert rendered == mutated_rendered
    assert row["input_text"] in rendered
    tokenizer = training_data.ByteTokenizer()
    assert tokenizer.encode(rendered, max_length=4096) == tokenizer.encode(
        mutated_rendered, max_length=4096,
    )


def test_rejects_merge_multi_hunk_secret_generated_and_shallow(tmp_path: Path) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    secret_repo = create_repo(root, 2, secret=True)
    generated_repo = create_repo(root, 3, generated=True)
    with pytest.raises(module.Stage12689Error, match="unsafe_or_nontext_blob"):
        module.read_change(secret_repo, git(secret_repo, "rev-parse", "HEAD"))
    with pytest.raises(module.Stage12689Error, match="unsafe_or_nontext_blob"):
        module.read_change(generated_repo, git(generated_repo, "rev-parse", "HEAD"))

    repo = create_repo(root, 4)
    path = repo / "module.py"
    baseline = [f"value_{index} = {index}\n" for index in range(30)]
    path.write_text("".join(baseline), encoding="utf-8")
    commit(repo, "Establish a long verified baseline", 2)
    baseline[1] = "value_1 = 100\n"
    baseline[28] = "value_28 = 2800\n"
    path.write_text("".join(baseline), encoding="utf-8")
    multi = commit(repo, "Change separated regions in one revision", 3)
    with pytest.raises(module.Stage12689Error, match="not_small_single_textual_hunk"):
        module.read_change(repo, multi)

    git(repo, "checkout", "-q", "-b", "side", "HEAD~1")
    (repo / "side.py").write_text("side = True\n", encoding="utf-8")
    commit(repo, "Prepare side branch", 3)
    git(repo, "checkout", "-q", "master")
    git(repo, "merge", "-q", "--no-ff", "side", "-m", "Merge side branch")
    with pytest.raises(module.Stage12689Error, match="root_or_merge_commit"):
        module.read_change(repo, git(repo, "rev-parse", "HEAD"))

    shallow_root = tmp_path / "shallow"
    shallow_root.mkdir()
    subprocess.run(
        ["git", "clone", "-q", "--depth", "1", f"file://{repo}", str(shallow_root / "copy")],
        check=True,
    )
    git(shallow_root / "copy", "remote", "set-url", "origin", "https://example.invalid/shallow.git")
    snapshots, counters = module.discover_repositories(shallow_root, 10)
    assert snapshots == []
    assert counters["shallow_repository"] == 1


def test_lineage_and_shared_patch_group_before_split(tmp_path: Path) -> None:
    module = load_module()
    change = module.Change(
        commit_oid="1" * 40, parent_oid="2" * 40, commit_tree_oid="3" * 40,
        parent_tree_oid="4" * 40, path="x.py", parent_blob_oid="5" * 40,
        child_blob_oid="6" * 40, parent_data=b"a\n", child_data=b"b\n", message="message\n",
        old_start=0, old_end=1, new_start=0, new_end=1, patch_fingerprint="7" * 64,
    )
    left = module.Snapshot(
        tmp_path / "a", "a" * 64, "https://example.invalid/a.git", "8" * 40, [change],
        ("root:shared", "commit:shared"), (("blob", "5" * 40),),
    )
    right = module.Snapshot(
        tmp_path / "b", "b" * 64, "https://example.invalid/b.git", "9" * 40, [change],
        ("root:other", "commit:shared"), (("blob", "0" * 40),),
    )
    module.assign_components([left, right])
    assert left.component_key == right.component_key
    assert left.split == right.split


def test_cross_split_overlap_counts_are_derived_from_final_proofs() -> None:
    module = load_module()
    proofs = [
        {"split": "train", "repository": "repo-a", "component": "component-a", "patch": "patch-a"},
        {"split": "eval", "repository": "repo-a", "component": "component-b", "patch": "patch-a"},
        {"split": "strict_eval", "repository": "repo-c", "component": "component-b", "patch": "patch-c"},
    ]
    assert module.cross_split_overlap_count(proofs, "repository") == 1
    assert module.cross_split_overlap_count(proofs, "component") == 1
    assert module.cross_split_overlap_count(proofs, "patch") == 1


def test_nonzero_finalized_overlap_fails_before_publication(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    populate_split_supply(root, module, {"train": 4, "eval": 1, "strict_eval": 1}, start_index=6100)
    monkeypatch.setattr(module, "cross_split_overlap_count", lambda _proofs, _key: 1)
    output = tmp_path / "out"
    with pytest.raises(module.Stage12689Error, match="finalized_cross_split_overlap"):
        module.build(root, output, tmp_path / "summary.json", max_repos=10, max_rows=10)
    assert not output.exists()


def test_complete_head_object_set_groups_repositories_regardless_role(tmp_path: Path) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    first = create_repo(root, 31)
    second = create_repo(root, 32)
    shared = "/* generated vendor identity retained for component grouping */\n"
    for index, repo in enumerate((first, second), start=2):
        shared_path = repo / "vendor/generated.min.js"
        shared_path.parent.mkdir()
        shared_path.write_text(shared, encoding="utf-8")
        commit(repo, f"Add shared repository context {index}", index)
        path = repo / "module.py"
        path.write_text(path.read_text() + f"value_{index} = {index}\n", encoding="utf-8")
        commit(repo, f"Extend distinct implementation {index}", index + 2)
    snapshots, _ = module.discover_repositories(root, 10)
    assert len(snapshots) == 2
    shared_oid = git(first, "rev-parse", "HEAD:vendor/generated.min.js")
    assert all(("blob", shared_oid) in snapshot.component_objects for snapshot in snapshots)
    assert all(any(object_type == "tree" for object_type, _oid in snapshot.component_objects) for snapshot in snapshots)
    module.assign_components(snapshots)
    assert snapshots[0].component_key == snapshots[1].component_key
    assert snapshots[0].split == snapshots[1].split


def test_dirfd_pending_create_and_noreplace_collision(tmp_path: Path) -> None:
    module = load_module()
    private = tmp_path / "private"
    private.mkdir()
    parent_fd = module.open_directory_nofollow(private)
    try:
        pending_fd = module.create_directory_at(parent_fd, "pending", mode=0o700)
        os.close(pending_fd)
        with pytest.raises(FileExistsError):
            module.create_directory_at(parent_fd, "pending", mode=0o700)
        os.mkdir("generation", 0o700, dir_fd=parent_fd)
        with pytest.raises(FileExistsError):
            module.rename_directory_noreplace(parent_fd, "pending", "generation")
        assert (private / "pending").is_dir()
        assert (private / "generation").is_dir()
    finally:
        os.close(parent_fd)


def test_pending_entry_substitution_is_rejected_before_rename(tmp_path: Path) -> None:
    module = load_module()
    private = tmp_path / "private"
    private.mkdir()
    parent_fd = module.open_directory_nofollow(private)
    pending_fd = module.create_directory_at(parent_fd, "pending", mode=0o700)
    try:
        os.rename("pending", "original-pending", src_dir_fd=parent_fd, dst_dir_fd=parent_fd)
        os.mkdir("pending", 0o700, dir_fd=parent_fd)
        with pytest.raises(module.Stage12689Error, match="pending_generation_inode_changed"):
            module.revalidate_directory_entry(parent_fd, "pending", pending_fd)
    finally:
        os.close(pending_fd)
        os.close(parent_fd)


def test_postrename_verification_requires_exact_regular_artifacts(tmp_path: Path) -> None:
    module = load_module()
    private = tmp_path / "private"
    private.mkdir()
    parent_fd = module.open_directory_nofollow(private)
    pending_fd = module.create_directory_at(parent_fd, "pending", mode=0o700)
    try:
        artifact = module.secure_write_at(pending_fd, "summary.json", b"{}\n", mode=0o400)
        identity = module.revalidate_directory_entry(parent_fd, "pending", pending_fd)
        module.rename_directory_noreplace(parent_fd, "pending", "generation")
        required = {"summary.json": artifact}
        module.verify_published_generation(
            parent_fd, "generation", identity, required, phase="published",
        )
        with pytest.raises(module.Stage12689Error, match="published_generation_entry_set_mismatch"):
            module.verify_published_generation(
                parent_fd,
                "generation",
                identity,
                {"summary.json": artifact, "missing.jsonl": artifact},
                phase="published",
            )
    finally:
        os.close(pending_fd)
        os.close(parent_fd)


def test_same_name_regular_artifact_substitution_is_rejected(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    populate_split_supply(root, module, {"train": 4, "eval": 1, "strict_eval": 1}, start_index=7100)
    output = tmp_path / "out"
    summary_path = tmp_path / "summary.json"
    real_rename = module.rename_directory_noreplace

    def substitute_summary(
        parent_fd: int, source_name: str, destination_name: str,
    ) -> None:
        real_rename(parent_fd, source_name, destination_name)
        generation = output / "private" / destination_name
        generation.chmod(0o700)
        summary = generation / "summary.json"
        original_bytes = summary.read_bytes()
        summary.rename(output / "private" / "displaced-summary.json")
        summary.write_bytes(original_bytes)
        summary.chmod(0o400)
        generation.chmod(0o500)

    monkeypatch.setattr(module, "rename_directory_noreplace", substitute_summary)
    with pytest.raises(
        module.Stage12689Error,
        match="published_generation_artifact_identity_mismatch:summary.json",
    ):
        module.build(root, output, summary_path, max_repos=10, max_rows=10)
    assert not summary_path.exists()
    assert not (output / "summary.json").exists()


def test_publication_parent_inode_revalidation_rejects_swap(tmp_path: Path) -> None:
    module = load_module()
    private = tmp_path / "private"
    private.mkdir()
    parent_fd = module.open_directory_nofollow(private)
    moved = tmp_path / "moved-private"
    private.rename(moved)
    private.mkdir()
    try:
        with pytest.raises(module.Stage12689Error, match="publication_parent_inode_changed"):
            module.revalidate_directory_identity(private, parent_fd)
    finally:
        os.close(parent_fd)


def test_later_eval_and_strict_snapshots_fill_reserved_caps(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    populate_split_supply(
        root, module, {"train": 4, "eval": 1, "strict_eval": 1}, start_index=9000,
    )
    snapshots, counters = module.discover_repositories(root, 10)
    module.assign_components(snapshots)
    by_split = {
        split: [snapshot for snapshot in snapshots if snapshot.split == split]
        for split in ("train", "eval", "strict_eval")
    }
    ordered = by_split["train"][:4] + by_split["eval"][:1] + by_split["strict_eval"][:1]
    for index, snapshot in enumerate(ordered):
        snapshot.component_key = f"{index:064x}"
        snapshot.split = "train" if index < 4 else "eval" if index == 4 else "strict_eval"
    monkeypatch.setattr(module, "discover_repositories", lambda _root, _max: (ordered, counters))
    monkeypatch.setattr(module, "assign_components", lambda _snapshots: None)

    summary = module.build(
        root, tmp_path / "out", tmp_path / "summary.json", max_repos=10, max_rows=10,
    )
    splits_by_component = {}
    for snapshot in ordered:
        splits_by_component.setdefault(snapshot.component_key, set()).add(snapshot.split)
    assert all(len(splits) == 1 for splits in splits_by_component.values())
    assert {snapshot.split for snapshot in ordered} == {"train", "eval", "strict_eval"}
    generation = tmp_path / "out" / summary["generation_relative_path"]
    rows = [json.loads(line) for line in (
        generation / "maintenance_history_train_eval_manifest.jsonl"
    ).read_text().splitlines()]
    assert sum(row["split"] == "train" for row in rows) == 8
    assert sum(row["split"] == "eval" for row in rows) == 1
    assert summary["materialized_model_row_count"] == 9
    assert summary["reserved_unmaterialized_strict_row_count"] == 1


@pytest.mark.parametrize("max_rows", [11, 19, 21])
def test_invalid_release_geometry_fails_before_discovery_or_output(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, max_rows: int,
) -> None:
    module = load_module()
    discovery_called = False

    def forbidden_discovery(_root: Path, _max_repos: int):
        nonlocal discovery_called
        discovery_called = True
        raise AssertionError("repository discovery must not run")

    monkeypatch.setattr(module, "discover_repositories", forbidden_discovery)
    output = tmp_path / "out"
    summary_path = tmp_path / "summary.json"
    with pytest.raises(module.Stage12689Error, match="invalid_max_rows_release_geometry"):
        module.build(
            tmp_path / "missing-source", output, summary_path,
            max_repos=10, max_rows=max_rows,
        )
    assert discovery_called is False
    assert not output.exists()
    assert not summary_path.exists()


def test_insufficient_strict_split_fails_without_output(tmp_path: Path) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    populate_split_supply(root, module, {"train": 4, "eval": 1}, start_index=10000)
    output = tmp_path / "out"
    summary_path = tmp_path / "summary.json"
    with pytest.raises(module.Stage12689Error) as captured:
        module.build(root, output, summary_path, max_repos=10, max_rows=10)
    assert str(captured.value) == "requested_split_caps_unfilled"
    assert not output.exists()
    assert not summary_path.exists()


def test_generation_id_binds_artifacts_schema_and_strict_commitment(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = load_module()
    payloads = {"manifest.jsonl": b"row\n", "ledger.jsonl": b"proof\n"}
    commitment = "a" * 64
    baseline = module.release_generation_id(payloads, commitment)
    assert baseline == module.release_generation_id(
        dict(reversed(list(payloads.items()))), commitment,
    )
    assert baseline != module.release_generation_id(
        {**payloads, "manifest.jsonl": b"changed\n"}, commitment,
    )
    assert baseline != module.release_generation_id(payloads, "b" * 64)
    monkeypatch.setattr(
        module, "ARTIFACT_SCHEMA_VERSION", module.ARTIFACT_SCHEMA_VERSION + 1,
    )
    assert baseline != module.release_generation_id(payloads, commitment)


def test_hidden_strict_counter_and_snapshot_mutations_do_not_change_public_release(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    populate_split_supply(
        root, module, {"train": 4, "eval": 1, "strict_eval": 1}, start_index=10500,
    )
    baseline = module.build(
        root, tmp_path / "baseline-out", tmp_path / "baseline-summary.json",
        max_repos=10, max_rows=10,
    )

    real_discover = module.discover_repositories
    real_overlap_gate = module.require_zero_finalized_overlaps
    captured_snapshots = []

    def discover_with_hidden_counter(source_root: Path, max_repos: int):
        snapshots, counters = real_discover(source_root, max_repos)
        counters["strict_eval_hidden_rejection_count"] = 999_999
        captured_snapshots[:] = snapshots
        return snapshots, counters

    def mutate_hidden_snapshot_after_proof_commitment(proofs):
        strict_snapshots = [
            snapshot for snapshot in captured_snapshots if snapshot.split == "strict_eval"
        ]
        assert strict_snapshots
        strict_snapshots[0].repo_key = "f" * 64
        return real_overlap_gate(proofs)

    monkeypatch.setattr(module, "discover_repositories", discover_with_hidden_counter)
    monkeypatch.setattr(
        module, "require_zero_finalized_overlaps",
        mutate_hidden_snapshot_after_proof_commitment,
    )
    mutated = module.build(
        root, tmp_path / "mutated-out", tmp_path / "mutated-summary.json",
        max_repos=10, max_rows=10,
    )
    assert "counters" not in baseline
    assert "counters" not in mutated
    assert mutated["strict_eval_commitment_sha256"] == baseline["strict_eval_commitment_sha256"]
    assert mutated["generation_id"] == baseline["generation_id"]
    assert mutated == baseline


def test_full_build_publishes_only_train_eval_plaintext(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    populate_split_supply(
        root, module, {"train": 4, "eval": 1, "strict_eval": 1}, start_index=8000,
    )
    output = tmp_path / "out"
    summary_path = tmp_path / "summary.json"
    prepared = module.prepare_release(root, max_repos=10, max_rows=10)
    monkeypatch.setattr(module, "prepare_release", lambda *_args, **_kwargs: prepared)
    summary = module.build(root, output, summary_path, max_repos=10, max_rows=10)
    assert summary["materialized_model_row_count"] == 9
    assert set(summary["objective_counts"]) == {
        "maintenance_commit_message_span_completion",
        "small_diff_exact_child_hunk_completion",
    }
    assert summary["reserved_unmaterialized_strict_row_count"] == 1
    assert len(summary["strict_eval_commitment_sha256"]) == 64
    assert summary["training_eligible_rows"] == 0
    assert summary["target_or_normalized_target_in_input_rows"] == 0
    assert summary["materialized_exact_reconstruction_verified_rows"] == 9
    assert summary["materialized_model_input_target_mutation_independent_rows"] == 9
    assert summary["component_identity_contract"] == "all_recursive_head_ls_tree_entries_object_type_and_oid_v1"
    assert summary["component_identity_exclusions"] == []
    assert summary["capacity_estimation_contract"] == (
        "buildable_objectives_after_patch_input_row_and_repository_caps_v1"
    )
    assert summary["split_allocation_contract"] == (
        "whole_component_exact_80_10_10_row_caps_v1"
    )
    assert summary["cross_split_repository_overlap"] == 0
    assert summary["cross_split_component_overlap"] == 0
    assert summary["cross_split_patch_fingerprint_overlap"] == 0
    assert summary["history_scan_complete"] is False
    assert "limited_history_window_requires_overlap_review" in summary["release_blockers"]
    assert "near_duplicate_patch_and_message_audit_required" in summary["release_blockers"]
    assert all(value is False for value in summary["authority"].values())
    generation = output / summary["generation_relative_path"]
    assert not any("strict" in path.name for path in generation.iterdir())
    assert summary["authoritative_summary_relative_path"] == f"{summary['generation_relative_path']}/summary.json"
    assert (generation / "summary.json").read_bytes() == summary_path.read_bytes()
    assert (generation / "summary.json").stat().st_mode & 0o777 == 0o400
    manifest = generation / "maintenance_history_train_eval_manifest.jsonl"
    rows = [json.loads(line) for line in manifest.read_text().splitlines()]
    assert rows and all(row["split"] in {"train", "eval"} for row in rows)
    materialized_objective_counts = {
        objective: sum(row["objective_family"] == objective for row in rows)
        for objective in {row["objective_family"] for row in rows}
    }
    assert summary["objective_counts"] == materialized_objective_counts
    assert sum(summary["objective_counts"].values()) == 9
    forbidden_subtraction_fields = {
        "row_count",
        "requested_split_caps",
        "split_counts",
        "row_count_equals_max_rows",
        "strict_eval_plaintext_materialized",
        "reserved_unmaterialized_strict_source_catalog_rows",
        "strict_rows_absent_from_artifacts",
        "language_counts",
        "status_counts",
    }
    assert forbidden_subtraction_fields.isdisjoint(summary)
    assert "counters" not in summary
    assert {key for key in summary if "strict" in key} == {
        "reserved_unmaterialized_strict_row_count",
        "strict_eval_commitment_sha256",
    }
    assert summary_path.read_bytes() == (output / "summary.json").read_bytes()
    assert summary == prepared.summary
    assert len(prepared.rows) == len(prepared.proofs) == 10
    proof_by_row_id = {proof["row_id"]: proof for proof in prepared.proofs}
    catalog_split = {
        entry["repository_key_sha256"]: entry["split"] for entry in prepared.catalog
    }
    assert all(
        row["split"] == proof_by_row_id[row["row_id"]]["split"]
        == catalog_split[row["source_provenance"]["repository_key_sha256"]]
        for row in prepared.rows
    )
    strict_rows = [row for row in prepared.rows if row["split"] == "strict_eval"]
    strict_proofs = [
        proof for proof in prepared.proofs if proof["split"] == "strict_eval"
    ]
    assert len(strict_rows) == len(strict_proofs) == summary[
        "reserved_unmaterialized_strict_row_count"
    ]
    assert module.stable(sorted(proof["row_sha256"] for proof in strict_proofs)) == summary[
        "strict_eval_commitment_sha256"
    ]
    for name, payload in prepared.public_payloads.items():
        assert (generation / name).read_bytes() == payload
    assert generation.stat().st_mode & 0o777 == 0o500
    for contract in summary["artifact_contract"].values():
        path = output / contract["relative_path"]
        assert module.file_sha256(path) == contract["sha256"]
        assert path.stat().st_mode & 0o777 == 0o400


def test_max_rows_is_enforced_inside_objective_loop(tmp_path: Path) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    populate_split_supply(
        root, module, {"train": 4, "eval": 1, "strict_eval": 1}, start_index=11000,
    )
    summary = module.build(
        root, tmp_path / "out", tmp_path / "summary.json", max_repos=10, max_rows=10,
    )
    assert summary["materialized_model_row_count"] == 9
    assert sum(summary["objective_counts"].values()) == 9
    assert summary["reserved_unmaterialized_strict_row_count"] == 1


def test_patch_fingerprint_dedup_quarantines_cross_component_copy(tmp_path: Path) -> None:
    module = load_module()
    root = tmp_path / "repos"
    root.mkdir()
    create_repo(root, 1, patch_value=2)
    create_repo(root, 2, patch_value=2)
    populate_split_supply(
        root, module, {"train": 5, "eval": 2, "strict_eval": 2}, start_index=12000,
    )
    snapshots, _ = module.discover_repositories(root, 20)
    module.assign_components(snapshots)
    duplicate_fingerprints = [
        snapshot.changes[0].patch_fingerprint
        for snapshot in snapshots
        if snapshot.local_path.name in {"repo-001", "repo-002"}
    ]
    assert len(duplicate_fingerprints) == 2
    assert len(set(duplicate_fingerprints)) == 1
    output = tmp_path / "out"
    summary = module.build(root, output, tmp_path / "summary.json", max_repos=20, max_rows=10)
    assert "counters" not in summary
    generation = output / summary["generation_relative_path"]
    ledger = [json.loads(line) for line in (
        generation / "train_eval_source_provenance_ledger.jsonl"
    ).read_text().splitlines()]
    components_by_patch = {}
    for proof in ledger:
        components_by_patch.setdefault(proof["patch_fingerprint_sha256"], set()).add(
            proof["content_component_sha256"]
        )
    assert all(len(components) == 1 for components in components_by_patch.values())
