from __future__ import annotations

import ast
import hashlib
import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts/build_stage12687_source_backed_python_foundational_corpus.py"


def load_module():
    spec = importlib.util.spec_from_file_location("stage12687", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def git(repo: Path, *args: str, env: dict[str, str] | None = None) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args], check=True, text=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env,
    )
    return result.stdout.strip()


def create_repo(source_root: Path, index: int) -> tuple[Path, str, str]:
    repo = source_root / f"repo-{index:03d}"
    repo.mkdir()
    git(repo, "init", "-q")
    git(repo, "config", "user.email", "fixture@example.invalid")
    git(repo, "config", "user.name", "Fixture")
    origin = f"https://example.com/repo-{index:03d}.git"
    git(repo, "remote", "add", "origin", origin)
    (repo / "LICENSE").write_text(
        "MIT License\n\nPermission is hereby granted, free of charge, to any person obtaining a copy.\n"
        "THE SOFTWARE IS PROVIDED AS IS.\n",
        encoding="utf-8",
    )
    for file_index in range(3):
        (repo / f"module_{file_index}.py").write_text(
            f"\nVALUE_{index}_{file_index} = {index + file_index}\n\n"
            f"def compute_{index}_{file_index}(value: int) -> int:\n"
            f"    adjusted = value + VALUE_{index}_{file_index}\n"
            "    assert adjusted >= value\n"
            "    return adjusted\n\n"
            f"class Holder_{index}_{file_index}:\n"
            "    enabled = True\n\n"
            f"def validate_{index}_{file_index}(candidate: int) -> bool:\n"
            "    normalized = max(candidate, 0)\n"
            "    return normalized == candidate\n",
            encoding="utf-8",
        )
    git(repo, "add", "LICENSE", "module_0.py", "module_1.py", "module_2.py")
    env = dict(os.environ)
    env.update({
        "GIT_AUTHOR_DATE": f"2020-01-{index % 28 + 1:02d}T00:00:00Z",
        "GIT_COMMITTER_DATE": f"2020-01-{index % 28 + 1:02d}T00:00:00Z",
    })
    git(repo, "commit", "-q", "-m", "fixture", env=env)
    return repo, origin, git(repo, "rev-parse", "HEAD")


def test_license_and_path_filters_are_fail_closed() -> None:
    module = load_module()
    padded = b"100644 blob " + b"a" * 40 + b"     285\tsrc/module.py\0"
    assert module.parse_ls_tree(padded) == [module.Blob(oid="a" * 40, size=285, path="src/module.py")]
    assert module.detect_license(
        "MIT License Permission is hereby granted, free of charge, THE SOFTWARE IS PROVIDED AS IS"
    ) == "MIT"
    assert module.detect_license("custom private terms") == "unknown"
    assert module.contains_high_confidence_secret(b"token = AKIA1234567890ABCDEF") is True
    assert module.contains_high_confidence_secret(b"token = ASIA1234567890ABCDEF") is True
    assert module.contains_high_confidence_secret(b"token = github_pat_12345678901234567890") is True
    assert module.contains_high_confidence_secret(b"token = sk-proj-12345678901234567890") is True
    assert module.contains_high_confidence_secret(b"ordinary source text") is False
    assert module.generated_content(b"# This file is automatically generated") is True
    assert module.generated_content(b"# Generated by source compiler") is True
    assert module.generated_content(b"x" * 5000 + b"# generated by ChatGPT") is True
    assert module.generated_content(b"x" * 5000 + b"# outputs generated by benchmark") is False
    assert module.path_allowed("src/module.py") is True
    assert module.path_allowed("vendor/module.py") is False
    assert module.path_allowed("src/generated_pb2.py") is False
    assert module.path_allowed("/absolute.py") is False
    assert module.path_allowed("src\\escape.py") is False
    assert module.sanitize_origin("https://user:secret@example.com/repo.git?token=secret") == "https://example.com/repo.git"
    assert module.sanitize_origin("git@example.com:owner/repo.git?token=secret") == "ssh://git@example.com/owner/repo.git"

    data = b"verified git blob"
    oid = hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()
    assert module.verify_blob_oid(oid, data) is True
    assert module.verify_blob_oid("0" * 40, data) is False
    assert module.target_is_stub_or_placeholder("raise NotImplementedError()") is True
    assert module.target_is_stub_or_placeholder("def pending():\n    pass") is True
    assert module.target_is_stub_or_placeholder("class Pending:\n    ...") is True
    assert module.target_is_stub_or_placeholder("value = 1  # TODO replace") is True
    assert module.target_is_stub_or_placeholder("def complete():\n    return 1") is False


def test_lineage_keys_force_forks_into_one_component() -> None:
    module = load_module()
    snapshots = [
        module.RepoSnapshot(Path("/a"), "a" * 64, "https://example.com/a.git", "1" * 40, "LICENSE", "2" * 40, "MIT", [], lineage_keys=("root:shared",)),
        module.RepoSnapshot(Path("/b"), "b" * 64, "https://example.com/b.git", "3" * 40, "LICENSE", "4" * 40, "MIT", [], lineage_keys=("root:shared",)),
    ]
    module.assign_components(snapshots)
    assert snapshots[0].component_key == snapshots[1].component_key
    assert snapshots[0].split == snapshots[1].split

    blobs = [
        module.RepoSnapshot(Path("/c"), "c" * 64, "https://example.com/c.git", "5" * 40, "LICENSE", "6" * 40, "MIT", [module.Blob("7" * 40, 300, "chosen.py")], component_blobs=(("8" * 40, 300),)),
        module.RepoSnapshot(Path("/d"), "d" * 64, "https://example.com/d.git", "9" * 40, "LICENSE", "a" * 40, "MIT", [module.Blob("b" * 40, 300, "different.py")], component_blobs=(("8" * 40, 300),)),
    ]
    module.assign_components(blobs)
    assert blobs[0].component_key == blobs[1].component_key


def test_parser_span_row_is_exact_and_target_independent() -> None:
    module = load_module()
    data = (
        b"VALUE = 3\n\n"
        b"def compute(value: int) -> int:\n"
        b"    adjusted = value + VALUE\n"
        b"    assert adjusted >= value\n"
        b"    return adjusted\n"
    )
    tree = ast.parse(data.decode("utf-8"))
    snapshot = module.RepoSnapshot(
        local_path=Path("/unused"), repo_key="a" * 64,
        origin_url="https://example.com/source.git", revision="b" * 40,
        license_path="LICENSE", license_oid="c" * 40, license_id="MIT",
        python_blobs=[], license_sha256="f" * 64, component_key="d" * 64, split="train",
    )
    blob = module.Blob(oid="e" * 40, size=len(data), path="src/module.py")
    spans = module.candidate_spans(data, tree, snapshot.repo_key, blob.path)
    assert spans
    built = module.build_row(snapshot, blob, data, tree, spans[0])
    assert built is not None
    row, proof = built
    assert row["input_text"].count(module.MASK) == 1
    assert row["target"]["decoder_text"]
    assert proof["byte_exact_reinsertion_verified"] is True
    assert proof["ast_roundtrip_verified"] is True

    sys.path.insert(0, str(ROOT / "legacy_src"))
    from agentkernel_lite.training_data import ByteTokenizer, _row_text

    mutated = json.loads(json.dumps(row))
    mutated["target"]["decoder_text"] = "different verified target"
    tokenizer = ByteTokenizer()
    assert tokenizer.encode(_row_text(row), max_length=2048) == tokenizer.encode(_row_text(mutated), max_length=2048)

    repeated = b"def first():\n    return None\n\ndef second():\n    return None\n"
    repeated_tree = ast.parse(repeated.decode())
    return_node = next(node for node in ast.walk(repeated_tree) if isinstance(node, ast.Return))
    repeated_lines = repeated.splitlines(keepends=True)
    repeated_span = (
        module.byte_position(repeated_lines, return_node.lineno, return_node.col_offset),
        module.byte_position(repeated_lines, return_node.end_lineno, return_node.end_col_offset),
        "Return",
    )
    repeated_blob = module.Blob(oid="9" * 40, size=len(repeated), path="repeated.py")
    assert module.build_row(snapshot, repeated_blob, repeated, repeated_tree, repeated_span) is None

    normalized = b"def first():\n    return None\n\ndef second():\n    # returnNone\n    return 1\n"
    normalized_tree = ast.parse(normalized.decode())
    normalized_node = next(node for node in ast.walk(normalized_tree) if isinstance(node, ast.Return))
    normalized_lines = normalized.splitlines(keepends=True)
    normalized_span = (
        module.byte_position(normalized_lines, normalized_node.lineno, normalized_node.col_offset),
        module.byte_position(normalized_lines, normalized_node.end_lineno, normalized_node.end_col_offset),
        "Return",
    )
    normalized_blob = module.Blob(oid="8" * 40, size=len(normalized), path="normalized.py")
    assert module.build_row(snapshot, normalized_blob, normalized, normalized_tree, normalized_span) is None


def test_cat_blobs_fails_closed_on_corruption_and_reaps_timeout(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    module = load_module()
    blob = module.Blob(oid="0" * 40, size=3, path="source.py")

    class ForgedProcess:
        returncode = 0

        def communicate(self, _input: bytes, timeout: int) -> tuple[bytes, bytes]:
            return f"{blob.oid} blob 3\n".encode("ascii") + b"bad\n", b""

    monkeypatch.setattr(module.subprocess, "Popen", lambda *args, **kwargs: ForgedProcess())
    with pytest.raises(module.Stage12687Error, match="git_blob_identity_mismatch"):
        module.cat_blobs(tmp_path, [blob])

    class TimedOutProcess:
        returncode = -9

        def __init__(self) -> None:
            self.killed = False
            self.calls = 0

        def communicate(self, _input: bytes | None = None, timeout: int | None = None) -> tuple[bytes, bytes]:
            self.calls += 1
            if self.calls == 1:
                raise module.subprocess.TimeoutExpired(["git"], timeout)
            return b"", b""

        def kill(self) -> None:
            self.killed = True

    timed_out = TimedOutProcess()
    monkeypatch.setattr(module.subprocess, "Popen", lambda *args, **kwargs: timed_out)
    with pytest.raises(module.Stage12687Error, match="git_cat_file_timeout"):
        module.cat_blobs(tmp_path, [blob])
    assert timed_out.killed is True
    assert timed_out.calls == 2


def test_secure_atomic_write_rejects_temporary_symlink(tmp_path: Path) -> None:
    module = load_module()
    target = tmp_path / "artifact.json"
    data = b"protected output\n"
    temporary = tmp_path / f".{target.name}.tmp.{os.getpid()}.{module.sha256_bytes(data)[:12]}"
    victim = tmp_path / "victim.txt"
    victim.write_text("unchanged", encoding="utf-8")
    temporary.symlink_to(victim)
    with pytest.raises(FileExistsError):
        module.secure_atomic_write(target, data, mode=0o600)
    assert victim.read_text(encoding="utf-8") == "unchanged"

    real_parent = tmp_path / "real-parent"
    real_parent.mkdir()
    linked_parent = tmp_path / "linked-parent"
    linked_parent.symlink_to(real_parent, target_is_directory=True)
    with pytest.raises(OSError):
        module.open_directory_nofollow(linked_parent)

    source = tmp_path / "source"
    destination = tmp_path / "destination"
    source.mkdir()
    destination.mkdir()
    parent_fd = module.open_directory_nofollow(tmp_path)
    try:
        with pytest.raises(module.Stage12687Error, match="immutable_generation_exists"):
            module.rename_noreplace(parent_fd, source.name, destination.name)
    finally:
        os.close(parent_fd)
    assert source.is_dir()
    assert destination.is_dir()


def test_publication_rejects_private_and_pending_symlinks(tmp_path: Path) -> None:
    module = load_module()
    victim = tmp_path / "victim"
    victim.mkdir()
    output = tmp_path / "symlinked-private"
    output.mkdir()
    (output / "private").symlink_to(victim, target_is_directory=True)
    with pytest.raises(OSError):
        module.publish_generation(
            output, "a" * 24, {"artifact.jsonl": b"safe\n"}, {"safe": True}
        )
    assert not any(victim.iterdir())

    output = tmp_path / "pending-symlink"
    private = output / "private"
    private.mkdir(parents=True)
    pending = private / f".pending-{'b' * 24}-{os.getpid()}"
    pending.symlink_to(victim, target_is_directory=True)
    with pytest.raises(FileExistsError):
        module.publish_generation(
            output, "b" * 24, {"artifact.jsonl": b"safe\n"}, {"safe": True}
        )
    assert pending.is_symlink()
    assert not any(victim.iterdir())


def test_publication_rejects_pending_directory_replacement(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    module = load_module()
    output = tmp_path / "artifact"
    generation_id = "c" * 24
    original_write = module.write_file_at
    writes = 0

    def replace_after_summary(directory_fd, name, data, *, mode):
        nonlocal writes
        identity = original_write(directory_fd, name, data, mode=mode)
        writes += 1
        if name == "summary.json":
            private = output / "private"
            pending = private / f".pending-{generation_id}-{os.getpid()}"
            displaced = private / ".displaced-pinned-pending"
            os.rename(pending, displaced)
            pending.mkdir()
        return identity

    monkeypatch.setattr(module, "write_file_at", replace_after_summary)
    with pytest.raises(module.Stage12687Error, match="pending_generation_inode_mismatch"):
        module.publish_generation(
            output, generation_id, {"artifact.jsonl": b"safe\n"}, {"safe": True}
        )
    assert writes == 2
    assert not (output / "private" / generation_id).exists()
    assert (output / "private" / ".displaced-pinned-pending" / "artifact.jsonl").is_file()


def test_publication_fsync_and_mode_order_is_durable(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    module = load_module()
    events: list[tuple[str, int, int | None]] = []
    original_fchmod = module.os.fchmod
    original_fsync = module.os.fsync
    original_rename = module.rename_noreplace

    def recording_fchmod(fd: int, mode: int) -> None:
        events.append(("fchmod", fd, mode))
        original_fchmod(fd, mode)

    def recording_fsync(fd: int) -> None:
        events.append(("fsync", fd, None))
        original_fsync(fd)

    def recording_rename(parent_fd: int, source: str, destination: str) -> None:
        events.append(("rename", parent_fd, None))
        original_rename(parent_fd, source, destination)

    monkeypatch.setattr(module.os, "fchmod", recording_fchmod)
    monkeypatch.setattr(module.os, "fsync", recording_fsync)
    monkeypatch.setattr(module, "rename_noreplace", recording_rename)
    output = tmp_path / "artifact"
    generation = module.publish_generation(
        output, "d" * 24, {"artifact.jsonl": b"safe\n"}, {"safe": True}
    )
    rename_index = next(index for index, event in enumerate(events) if event[0] == "rename")
    file_mode_events = [
        (index, event) for index, event in enumerate(events)
        if event[0] == "fchmod" and event[2] == 0o400
    ]
    assert len(file_mode_events) == 2
    for mode_index, (_, fd, _) in file_mode_events:
        assert any(
            event[0] == "fsync" and event[1] == fd
            for event in events[mode_index + 1:rename_index]
        )
    pending_mode_index, pending_mode = next(
        (index, event) for index, event in enumerate(events)
        if event[0] == "fchmod" and event[2] == 0o500
    )
    assert pending_mode_index < rename_index
    assert any(
        event[0] == "fsync" and event[1] == pending_mode[1]
        for event in events[pending_mode_index + 1:rename_index]
    )
    rename_parent_fd = events[rename_index][1]
    assert any(
        event[0] == "fsync" and event[1] == rename_parent_fd
        for event in events[rename_index + 1:]
    )
    assert generation.stat().st_mode & 0o777 == 0o500
    assert (generation / "artifact.jsonl").stat().st_mode & 0o777 == 0o400
    assert (generation / "summary.json").stat().st_mode & 0o777 == 0o400


@pytest.mark.parametrize("max_rows", [0, 9, 11, 19, 21])
def test_invalid_split_geometry_fails_before_discovery_or_output(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, max_rows: int
) -> None:
    module = load_module()
    source_root = tmp_path / "repos"
    source_root.mkdir()
    monkeypatch.setattr(
        module,
        "discover_repositories",
        lambda *_args, **_kwargs: pytest.fail("discovery must not run"),
    )
    output = tmp_path / "artifact"
    with pytest.raises(
        module.Stage12687Error, match="^invalid_max_rows_exact_80_10_10_required$"
    ):
        module.build(
            source_root, output, tmp_path / "summary.json",
            max_repos=1, max_rows=max_rows,
        )
    assert not output.exists()


def test_overlap_audit_is_all_split_internal_and_train_eval_public() -> None:
    module = load_module()
    proofs = [
        {"split": "train", "source_file_sha256": "a" * 64},
        {"split": "eval", "source_file_sha256": "b" * 64},
        {"split": "strict_eval", "source_file_sha256": "a" * 64},
    ]
    internal = module.finalized_cross_split_overlap(proofs, "source_file_sha256")
    public = module.finalized_cross_split_overlap(proofs[:2], "source_file_sha256")
    assert internal["overlap_count"] == 1
    assert public["overlap_count"] == 0


def test_full_build_separates_strict_and_pins_artifacts(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    module = load_module()
    source_root = tmp_path / "repos"
    source_root.mkdir()
    wanted = {"train", "eval", "strict_eval"}
    found: set[str] = set()
    for index in range(80):
        _repo, origin, revision = create_repo(source_root, index)
        repo_key = module.stable([origin, revision])
        component = module.stable([repo_key])
        bucket = int(component[:8], 16) % 20
        found.add("train" if bucket < 16 else "eval" if bucket < 18 else "strict_eval")
        if found == wanted:
            break
    assert found == wanted

    output = tmp_path / "artifact"
    summary_path = tmp_path / "summary.json"
    real_prepare = module.prepare_release
    captured = []

    def capture_prepared(*args, **kwargs):
        prepared = real_prepare(*args, **kwargs)
        captured.append(prepared)
        return prepared

    monkeypatch.setattr(module, "prepare_release", capture_prepared)
    summary = module.build(source_root, output, summary_path, max_repos=80, max_rows=10)
    assert len(captured) == 1
    prepared = captured[0]
    assert summary["public_split_counts"] == {"eval": 1, "train": 8}
    assert summary["training_eligible_rows"] == 0
    assert summary["authoritative_summary_relative_path"].endswith("/summary.json")
    assert summary["generation_and_authoritative_summary_transactional"] is True
    assert summary["external_summary_mirrors_are_nonauthoritative"] is True
    assert summary["artifact_schema_version"] == 4
    assert summary["materialized_model_row_count"] == 9
    assert summary["reserved_unmaterialized_strict_row_count"] == 1
    assert len(summary["strict_eval_commitment_sha256"]) == 64
    assert summary["stub_or_placeholder_target_rows"] == 0
    assert all(value is False for value in summary["authority"].values())
    assert all(
        metric["overlap_count"] == 0
        for metric in summary["public_split_overlap_metrics"].values()
    )
    assert "counters" not in summary
    strict_public_keys = {
        key for key in summary
        if "strict" in key and key not in {"authority", "release_blockers"}
    }
    assert strict_public_keys == {
        "reserved_unmaterialized_strict_row_count",
        "strict_eval_commitment_sha256",
    }
    assert summary["maximum_rows_from_one_repository"] <= module.MAX_ROWS_PER_REPO
    assert summary["source_catalog_rows"] == summary["repository_snapshots"]
    assert summary["distinct_model_example_hashes"] == 9
    assert summary["distinct_semantic_example_hashes"] == 9

    private = output / summary["generation_relative_path"]
    train_eval = [json.loads(line) for line in (private / "foundational_train_eval_manifest.jsonl").read_text().splitlines()]
    train_proofs = [json.loads(line) for line in (private / "train_eval_source_provenance_ledger.jsonl").read_text().splitlines()]
    train_catalog = [json.loads(line) for line in (private / "train_eval_source_catalog.jsonl").read_text().splitlines()]
    catalog = train_catalog
    assert len(train_eval) == 9
    assert set(summary["artifact_contract"]) == {
        "foundational_train_eval_manifest.jsonl",
        "train_eval_source_provenance_ledger.jsonl",
        "train_eval_source_catalog.jsonl",
    }
    assert not any("strict" in path.name for path in private.iterdir())
    assert (private / "summary.json").read_bytes() == summary_path.read_bytes()
    assert {row["split"] for row in train_eval} == {"train", "eval"}
    assert len(train_proofs) == len(train_eval)
    assert all(row["split"] != "strict_eval" for row in train_proofs + train_catalog)
    assert all(not module.target_is_stub_or_placeholder(row["target"]["decoder_text"]) for row in train_eval)
    assert all(row["input_text"].count(module.MASK) == 1 for row in train_eval)
    assert all(row["eligible_python_blob_count"] >= row["selected_python_blob_count"] for row in catalog)
    assert all(len(row["eligible_python_blob_set_sha256"]) == 64 for row in catalog)
    assert all(row["root_commit_git_oids"] and row["tree_git_oids"] for row in catalog)
    assert all(row["remote_lineage_url_sha256s"] for row in catalog)
    assert summary_path.read_bytes() == (output / "summary.json").read_bytes()
    assert summary == prepared.summary
    assert len(prepared.rows) == len(prepared.proofs) == 10
    proof_by_row_id = {proof["row_id"]: proof for proof in prepared.proofs}
    catalog_split = {
        entry["repository_key_sha256"]: entry["split"] for entry in prepared.catalog
    }
    assert all(
        row["split"] == proof_by_row_id[row["row_id"]]["split"]
        == catalog_split[row["source_provenance"]["repository_key_sha256"]]
        for row in prepared.rows
    )
    strict_rows = [row for row in prepared.rows if row["split"] == "strict_eval"]
    strict_proofs = [
        proof for proof in prepared.proofs if proof["split"] == "strict_eval"
    ]
    assert len(strict_rows) == len(strict_proofs) == summary[
        "reserved_unmaterialized_strict_row_count"
    ]
    assert module.stable(sorted(proof["row_sha256"] for proof in strict_proofs)) == summary[
        "strict_eval_commitment_sha256"
    ]
    for name, payload in prepared.public_payloads.items():
        assert (private / name).read_bytes() == payload
    assert private.stat().st_mode & 0o777 == 0o500
    for name, contract in summary["artifact_contract"].items():
        path = output / contract["relative_path"]
        assert module.file_sha256(path) == contract["sha256"]
        assert sum(1 for _ in path.open()) == contract["rows"]
        assert path.stat().st_mode & 0o777 == 0o400

    with pytest.raises(module.Stage12687Error) as error:
        module.build(source_root, tmp_path / "too_large", tmp_path / "too_large.json", max_repos=80, max_rows=10_000)
    assert str(error.value) == "requested_split_caps_unfilled"
    assert not (tmp_path / "too_large").exists()

    with pytest.raises(module.Stage12687Error, match="immutable_generation_exists"):
        module.build(source_root, output, summary_path, max_repos=80, max_rows=10)

    original_build_row = module.build_row

    def mutate_strict(snapshot, *args, **kwargs):
        built = original_build_row(snapshot, *args, **kwargs)
        if built is None or snapshot.split != "strict_eval":
            return built
        row, proof = built
        proof = dict(proof)
        proof["row_sha256"] = module.sha256_bytes(
            ("changed-strict:" + proof["row_sha256"]).encode("ascii")
        )
        return row, proof

    module.build_row = mutate_strict
    changed = module.build(
        source_root, output, summary_path, max_repos=80, max_rows=10
    )
    assert changed["generation_id"] != summary["generation_id"]
    assert changed["strict_eval_commitment_sha256"] != summary["strict_eval_commitment_sha256"]
    first_authoritative = json.loads(
        (output / summary["authoritative_summary_relative_path"]).read_text()
    )
    changed_authoritative = json.loads(
        (output / changed["authoritative_summary_relative_path"]).read_text()
    )
    assert first_authoritative == summary
    assert changed_authoritative == changed
    permitted = {
        "generation_id",
        "generation_relative_path",
        "authoritative_summary_relative_path",
        "strict_eval_commitment_sha256",
        "artifact_contract",
    }
    assert {
        key: value for key, value in summary.items() if key not in permitted
    } == {
        key: value for key, value in changed.items() if key not in permitted
    }
