#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,os,shutil,subprocess,time
from collections import Counter
from pathlib import Path
from typing import Any
ROOT=Path('runs/local/artifacts/stage12055_controlled_semantic_fail_to_pass_supplement_rows').resolve(); FIXTURE_ROOT=ROOT/'fixture_repos'; ROWS=ROOT/'controlled_semantic_fail_to_pass_supplement_rows.jsonl'; SUMMARY=ROOT/'controlled_semantic_fail_to_pass_supplement_rows.json'; SUMMARY_MIRROR=Path('runs/summaries/stage12055_controlled_semantic_fail_to_pass_supplement_rows.json'); LABELS=list('ABCDEFGH')
TRANSITION_TEXT={'PASS_TO_PASS':'focused verifier executed from local source and passed','PASS_CURRENT_BUILD_AND_RUN':'build and runnable verifier both passed','PASS_CURRENT_BUILD':'build or collection passed but runnable verifier body did not execute','FAIL_TO_PASS':'controlled broken state failed and restored or repaired source passed','NOT_EXERCISED':'command did not exercise or collect the selected verifier','INSUFFICIENT_EVIDENCE':'environment is underhydrated so no trustworthy transition is available','FAIL_TO_FAIL':'verifier failed in the current local source state','VERIFIER_REMOVED':'verifier evidence was removed and the row should abstain'}
FIXTURES=[
 {'id':'python_8_query_param_preserved','files':{'logic.py':'def serialize(params):\n    return "&".join(f"{k}={v}" for k,v in params)\n','test_logic.py':'from logic import serialize\ndef test_query_param_preserved():\n    assert serialize([("b",2),("a",1)])=="b=2&a=1"\n'},'find':'return "&".join(f"{k}={v}" for k,v in params)','replace':'return "&".join(f"{k}={v}" for k,v in sorted(params))','selected':'test_logic.py::test_query_param_preserved'},
 {'id':'python_9_escape_html','files':{'logic.py':'def escape(s):\n    return s.replace("&", "&amp;").replace("<", "&lt;")\n','test_logic.py':'from logic import escape\ndef test_escape_html():\n    assert escape("a&<b")=="a&amp;&lt;b"\n'},'find':'return s.replace("&", "&amp;").replace("<", "&lt;")','replace':'return s.replace("<", "&lt;")','selected':'test_logic.py::test_escape_html'},
 {'id':'python_10_status_mapping','files':{'logic.py':'def status(code):\n    return "retry" if code in {429, 503} else "fail"\n','test_logic.py':'from logic import status\ndef test_status_mapping():\n    assert status(429)=="retry"\n    assert status(503)=="retry"\n    assert status(500)=="fail"\n'},'find':'return "retry" if code in {429, 503} else "fail"','replace':'return "retry" if code == 429 else "fail"','selected':'test_logic.py::test_status_mapping'},
 {'id':'python_11_path_normalization','files':{'logic.py':'def clean(path):\n    return path.strip("/")\n','test_logic.py':'from logic import clean\ndef test_path_normalization():\n    assert clean("/api/v1/")=="api/v1"\n'},'find':'return path.strip("/")','replace':'return path.lstrip("/")','selected':'test_logic.py::test_path_normalization'},
]
def write_json(p:Path,x:Any): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def write_jsonl(p:Path,rows): p.write_text(''.join(json.dumps(r,sort_keys=True)+'\n' for r in rows))
def run(cwd,cmd,name):
 env=os.environ.copy(); env.update({'CUDA_VISIBLE_DEVICES':'','NVIDIA_VISIBLE_DEVICES':'','TMPDIR':str(ROOT/'tmp'),'TEMP':str(ROOT/'tmp'),'TMP':str(ROOT/'tmp')}); (ROOT/'tmp').mkdir(parents=True,exist_ok=True); (ROOT/'logs').mkdir(parents=True,exist_ok=True); t=time.time(); proc=subprocess.run(cmd,cwd=str(cwd),env=env,text=True,capture_output=True,stdin=subprocess.DEVNULL,timeout=30,check=False); out={'command':cmd,'cwd':str(cwd),'returncode':proc.returncode,'timed_out':False,'duration_sec':round(time.time()-t,3),'stdout_tail':(proc.stdout or '')[-2000:],'stderr_tail':(proc.stderr or '')[-2000:]}; write_json(ROOT/'logs'/f'{name}.json',out); return {**out,'log_path':str(ROOT/'logs'/f'{name}.json')}
def options(row_id,lang):
 keyed=[(hashlib.sha256(f'{row_id}::{v}'.encode()).hexdigest(),v,t) for v,t in TRANSITION_TEXT.items()]
 return [{'label':lab,'canonical_value':v,'value':v,'text':t,'role':'verifier_transition_status','artifact_type':f'{lang}_verifier_status'} for lab,(_,v,t) in zip(LABELS,sorted(keyed))]
def build(spec):
 root=FIXTURE_ROOT/spec['id'];
 if root.exists(): shutil.rmtree(root)
 root.mkdir(parents=True)
 for n,t in spec['files'].items(): (root/n).write_text(t)
 cmd=['python','-m','pytest','-q','-c','/dev/null','test_logic.py']; src=root/'logic.py'; original=src.read_text(); baseline=run(root,cmd,f"{spec['id']}_baseline"); src.write_text(original.replace(spec['find'],spec['replace'],1)); mutant=run(root,cmd,f"{spec['id']}_mutant"); src.write_text(original); restored=run(root,cmd,f"{spec['id']}_restored"); admitted=baseline['returncode']==0 and mutant['returncode']!=0 and restored['returncode']==0 and src.read_text()==original; card={'fixture_id':spec['id'],'baseline':baseline,'mutant':mutant,'restored':restored,'admitted':admitted}
 if not admitted: return None,card
 semantic='FAIL_TO_PASS'; row_id=f"stage12055::stage12055_python_semantic_fixture::{spec['id']}"; opts=options(row_id,'python'); lab=next(o['label'] for o in opts if o['canonical_value']==semantic); prompt='\n'.join(['Language: python','Perspective: transition_verifier_transition','Task: choose the verifier transition proven by baseline, semantic mutation, and restored-source evidence.','Repository family: stage12055_python_semantic_fixture',f'Fixture root: {root}','Source file mutated: logic.py',f"Selected verifier: {spec['selected']}",f"Baseline rc: {baseline['returncode']} tail: {baseline['stdout_tail'][-500:]}",f"Mutant rc: {mutant['returncode']} tail: {(mutant['stdout_tail'] or mutant['stderr_tail'])[-500:]}",f"Restored rc: {restored['returncode']} tail: {restored['stdout_tail'][-500:]}",'Options:',*[f"{o['label']}. {o['text']}" for o in opts],'Answer:'])
 return {'row_id':row_id,'root_id':row_id,'root_lineage_key':f"stage12055::stage12055_python_semantic_fixture::{spec['id']}",'source_root_id':row_id,'source_bundle_id':row_id,'repo_id':'stage12055_python_semantic_fixture','repo_family':'stage12055_python_semantic_fixture','language_family':'python','task_type':'transition_verifier_transition','split':'train','split_role':'stage12055_controlled_semantic_fail_to_pass_supplement_train_support_only','train_support_only':True,'strict_eval_eligible':False,'source_heldout_admissible':False,'selected_test_anchor':True,'verifier_anchor':True,'input_text':prompt,'prompt_text':prompt,'target_text':lab,'decoder_text':lab,'bounded_choice_target_label':lab,'target':{'bounded_choice_target_label':lab,'decoder_text':lab,'semantic_value':semantic},'opaque_options':opts,'observed_verifier_transition':semantic,'semantic_mutation':{'mutation_kind':spec['id'],'source_file':'logic.py','baseline_returncode':0,'mutant_returncode':mutant['returncode'],'restored_returncode':0},'anti_cheat':{'deterministic_option_shuffle':True,'target_label_not_visible_before_options':True,'target_value_not_visible_before_options':True,'singleton_options':False,'controlled_fixture_train_support_only':True,'semantic_mutation_not_syntax_only':True,'baseline_mutant_restore_all_observed':True,'train_support_only':True},'standalone_projection_source':{'projection_mode':'stage12055_controlled_semantic_fail_to_pass_supplement_rows','fixture_repo':str(root),'selected_verifier_path':spec['selected'],'source_file':'logic.py','observed_verifier_transition':semantic,'tool_or_verifier_observation':{'baseline':baseline,'mutant':mutant,'restored':restored}}},card
def main():
 ROOT.mkdir(parents=True,exist_ok=True); SUMMARY_MIRROR.parent.mkdir(parents=True,exist_ok=True); rows=[]; cards=[]
 for spec in FIXTURES:
  row,card=build(spec); cards.append(card); print(f"{spec['id']} admitted={card['admitted']}",flush=True)
  if row: rows.append(row)
 write_jsonl(ROWS,rows); summary={'stage':'stage12055_controlled_semantic_fail_to_pass_supplement_rows','rows_path':str(ROWS),'fixture_root':str(FIXTURE_ROOT),'attempted_fixtures':len(FIXTURES),'admitted_rows':len(rows),'unique_roots':len({r['root_lineage_key'] for r in rows}),'language_counts':dict(Counter(r['language_family'] for r in rows)),'status_counts':dict(Counter(r['observed_verifier_transition'] for r in rows)),'repo_family_counts':dict(Counter(r['repo_family'] for r in rows)),'probe_cards':cards,'decision':'admit_controlled_semantic_fail_to_pass_supplement_train_support' if rows else 'no_rows_admitted','claim_boundary':'Controlled semantic fixtures are train-support only; not source-heldout or strict eval evidence.','next_stage_recommendation':{'stage':'stage12056_transition_support_rollup_v35','action':'Merge supplemental FAIL_TO_PASS rows and verify Transition-Root-250 floors.'}}
 write_json(SUMMARY,summary); write_json(SUMMARY_MIRROR,summary); print(json.dumps({k:summary[k] for k in ['decision','admitted_rows','language_counts','status_counts','next_stage_recommendation']},indent=2,sort_keys=True))
if __name__=='__main__': main()
