#!/usr/bin/env python3
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

try:
    from scripts.diagnostic_ticket_contract import AUTHORITY_CLOSED
except ModuleNotFoundError:  # pragma: no cover
    from diagnostic_ticket_contract import AUTHORITY_CLOSED  # type: ignore

ROOT = Path(__file__).resolve().parents[1]
STAGE = 9002
NAME = "stage9002_one_run_training_ticket_blocker_audit"
REGISTRY = ROOT / "runs/local/artifacts/reconstructed_stage_registry.json"
SUMMARY = ROOT / "runs/summaries" / f"{NAME}.json"
DOC = ROOT / "docs" / "ONE_RUN_TRAINING_TICKET_BLOCKER_AUDIT_STAGE9002.md"
OUT_DIR = ROOT / "runs/local/artifacts" / NAME
AUDIT = OUT_DIR / "one_run_training_ticket_blocker_audit.json"

SOURCE_SUMMARY = ROOT / "runs/summaries/stage9000_one_run_bounded_training_ticket_contract.json"
SOURCE_CONTRACT = ROOT / "runs/local/artifacts/stage9000_one_run_bounded_training_ticket_contract/one_run_bounded_training_ticket_contract.json"

# Future artifacts. Absence is expected until earlier gates actually execute.
FUTURE_DRY_RUN_DIR = ROOT / "runs/local/artifacts/future_stage9xxx_trainer_contract_only_dry_run_execution"
FUTURE_REQUIRED_ARTIFACTS = {
    "trainer_contract_dry_run_report.json": FUTURE_DRY_RUN_DIR / "trainer_contract_dry_run_report.json",
    "loss_mask_enforcement_audit.json": FUTURE_DRY_RUN_DIR / "loss_mask_enforcement_audit.json",
    "telemetry_artifact_plan.json": FUTURE_DRY_RUN_DIR / "telemetry_artifact_plan.json",
    "no_model_forward_proof.json": FUTURE_DRY_RUN_DIR / "no_model_forward_proof.json",
    "no_training_execution_proof.json": FUTURE_DRY_RUN_DIR / "no_training_execution_proof.json",
    "next_one_run_training_ticket_input.json": FUTURE_DRY_RUN_DIR / "next_one_run_training_ticket_input.json",
}

REQUIRED_READINESS_CONDITIONS = [
    "stage9000_contract_passed",
    "trainer_dry_run_execution_report_present",
    "loss_mask_enforcement_audit_present",
    "telemetry_artifact_plan_present",
    "no_model_forward_proof_present",
    "no_training_execution_proof_present",
    "next_one_run_training_ticket_input_present",
    "dry_run_report_passed",
    "loss_mask_enforcement_passed",
    "bounded_training_ticket_input_scope_valid",
]

BLOCKING_REASONS_WHEN_MISSING = {
    "trainer_dry_run_execution_report_present": "trainer contract-only dry run has not executed",
    "loss_mask_enforcement_audit_present": "loss-mask enforcement has not been runtime-audited",
    "telemetry_artifact_plan_present": "trainer telemetry output plan has not been generated by a dry run",
    "no_model_forward_proof_present": "dry run has not proven it stopped before model forward",
    "no_training_execution_proof_present": "dry run has not proven no training occurred",
    "next_one_run_training_ticket_input_present": "bounded training ticket input has not been materialized by the dry run",
    "dry_run_report_passed": "no passing dry-run report is available",
    "loss_mask_enforcement_passed": "no passing loss-mask enforcement audit is available",
    "bounded_training_ticket_input_scope_valid": "training ticket input scope cannot be validated before it exists",
}

FORBIDDEN_OPERATIONS = [
    "INSTANTIATE_TRAINING_TICKET_NOW",
    "RUN_TRAINING_NOW",
    "LOAD_MODEL_WEIGHTS",
    "CREATE_OPTIMIZER",
    "READ_DATASET_ROWS",
    "READ_REPOSITORY_SOURCE_BODY",
    "WRITE_TO_ARXIV",
    "PROMOTE_MODEL",
    "MERGE_MODEL",
    "AUTHORIZE_DECODER_CE",
    "AUTHORIZE_DENOISE_CE",
]


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}


def artifact_passed(path: Path) -> bool:
    data = load_json(path)
    metrics = data.get("metrics") or {}
    return data.get("passed") is True or data.get("audit_passed") is True or metrics.get("passed") is True or metrics.get("audit_passed") is True


def build_audit(registry: dict[str, Any]) -> dict[str, Any]:
    source_summary = load_json(SOURCE_SUMMARY)
    source_contract = load_json(SOURCE_CONTRACT)
    present = {name: path.exists() for name, path in FUTURE_REQUIRED_ARTIFACTS.items()}
    readiness = {
        "stage9000_contract_passed": source_summary.get("passed") is True and SOURCE_CONTRACT.exists(),
        "trainer_dry_run_execution_report_present": present["trainer_contract_dry_run_report.json"],
        "loss_mask_enforcement_audit_present": present["loss_mask_enforcement_audit.json"],
        "telemetry_artifact_plan_present": present["telemetry_artifact_plan.json"],
        "no_model_forward_proof_present": present["no_model_forward_proof.json"],
        "no_training_execution_proof_present": present["no_training_execution_proof.json"],
        "next_one_run_training_ticket_input_present": present["next_one_run_training_ticket_input.json"],
        "dry_run_report_passed": artifact_passed(FUTURE_REQUIRED_ARTIFACTS["trainer_contract_dry_run_report.json"]),
        "loss_mask_enforcement_passed": artifact_passed(FUTURE_REQUIRED_ARTIFACTS["loss_mask_enforcement_audit.json"]),
        "bounded_training_ticket_input_scope_valid": False,
    }
    blocking_reasons = {
        condition: BLOCKING_REASONS_WHEN_MISSING[condition]
        for condition, ok in readiness.items()
        if not ok and condition in BLOCKING_REASONS_WHEN_MISSING
    }
    checks = {
        "source_stage9000_present": SOURCE_SUMMARY.exists() and SOURCE_CONTRACT.exists(),
        "source_stage9000_passed": source_summary.get("passed") is True,
        "source_stage9000_keeps_training_closed": (source_summary.get("metrics") or {}).get("training_ticket_authorized_now") is False,
        "source_stage9000_requires_dry_run_inputs": set(source_contract.get("required_inputs") or []) >= set(FUTURE_REQUIRED_ARTIFACTS),
        "required_readiness_conditions_recorded": len(REQUIRED_READINESS_CONDITIONS) >= 10,
        "forbidden_operations_recorded": len(FORBIDDEN_OPERATIONS) >= 11,
        "ticket_instantiation_blocked": bool(blocking_reasons),
        "authority_counts_zero": not any(((registry.get("metrics") or {}).get("authority_counts") or {}).get(key, 0) for key in AUTHORITY_CLOSED),
    }
    return {
        "stage": STAGE,
        "stage_name": NAME,
        "status": "ONE_RUN_TRAINING_TICKET_BLOCKER_AUDIT_NO_EXECUTION",
        "future_required_artifacts": {name: str(path.relative_to(ROOT)) for name, path in FUTURE_REQUIRED_ARTIFACTS.items()},
        "readiness": readiness,
        "blocking_reasons": blocking_reasons,
        "forbidden_operations": FORBIDDEN_OPERATIONS,
        "checks": checks,
        "metrics": {
            "required_readiness_conditions": len(REQUIRED_READINESS_CONDITIONS),
            "future_required_artifacts": len(FUTURE_REQUIRED_ARTIFACTS),
            "missing_future_artifacts": sum(1 for ok in present.values() if not ok),
            "blocking_reasons": len(blocking_reasons),
            "ticket_instantiation_ready": False,
            "training_ticket_authorized_now": False,
            "training_ticket_instantiated_now": False,
            "training_executed_now": False,
            "model_weights_loaded": False,
            "optimizer_created": False,
            "dataset_rows_loaded": False,
            "repository_source_bodies_loaded": False,
            "arxiv_write_authorized": False,
            "training_authorized": False,
            "data_mining_authorized": False,
            "model_execution_attempted": False,
            "runtime_authorized_flag": False,
            "promotion_authorized": False,
            "model_merge_authorized": False,
            "decoder_ce_authorized": False,
            "denoise_ce_authorized": False,
        },
        "authority": dict(AUTHORITY_CLOSED),
        "decision": "One-run training ticket instantiation is blocked until a real trainer contract-only dry run produces all required passing artifacts. No training ticket is instantiated by this audit.",
    }


def validate_audit(card: dict[str, Any]) -> list[str]:
    failures = [key for key, value in card["checks"].items() if value is not True]
    if any((card.get("authority") or {}).values()):
        failures.append("authority_open")
    if card["metrics"].get("ticket_instantiation_ready") is not False:
        failures.append("ticket_instantiation_ready")
    for required in ["trainer_dry_run_execution_report_present", "loss_mask_enforcement_audit_present", "next_one_run_training_ticket_input_present"]:
        if required not in card.get("readiness", {}):
            failures.append(f"missing_readiness:{required}")
    for key in [
        "training_ticket_authorized_now",
        "training_ticket_instantiated_now",
        "training_executed_now",
        "model_weights_loaded",
        "optimizer_created",
        "dataset_rows_loaded",
        "repository_source_bodies_loaded",
        "arxiv_write_authorized",
        "training_authorized",
        "data_mining_authorized",
        "model_execution_attempted",
        "runtime_authorized_flag",
        "promotion_authorized",
        "model_merge_authorized",
        "decoder_ce_authorized",
        "denoise_ce_authorized",
    ]:
        if card["metrics"].get(key) is not False:
            failures.append(key)
    return failures


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    registry = load_json(REGISTRY) or {"rows": [], "metrics": {}}
    card = build_audit(registry)
    failures = validate_audit(card)
    AUDIT.write_text(json.dumps(card, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    summary = {
        "stage": STAGE,
        "stage_name": NAME,
        "passed": not failures,
        "authority": dict(AUTHORITY_CLOSED),
        "metrics": {**dict(AUTHORITY_CLOSED), "authority_rows": 0, "failures": failures, **card["metrics"]},
        "artifacts": {"audit": str(AUDIT.relative_to(ROOT))},
        "decision": card["decision"],
        "next_best_step": "Execute a trainer contract-only dry run only after the earlier manifest/row-sample gates have actually produced inputs. Until then, keep one-run training ticket instantiation blocked.",
        "created_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    SUMMARY.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    DOC.write_text("\n".join([
        "# Stage9002 One-Run Training Ticket Blocker Audit",
        "",
        f"Passed: `{summary['passed']}`",
        "",
        "This stage audits readiness for a future one-run bounded training ticket. It deliberately blocks ticket instantiation until a real trainer contract-only dry run has produced all required passing artifacts.",
        "",
        f"Missing future artifacts: `{summary['metrics']['missing_future_artifacts']}`",
        f"Blocking reasons: `{summary['metrics']['blocking_reasons']}`",
        f"Training ticket authorized now: `{summary['metrics']['training_ticket_authorized_now']}`",
        "",
    ]), encoding="utf-8")
    rows = [row for row in registry.get("rows", []) if row.get("stage_name") != NAME]
    rows.append({"stage": STAGE, "stage_name": NAME, "passed": summary["passed"], "path": str(SUMMARY), "authority": dict(AUTHORITY_CLOSED), "next_best_step": summary["next_best_step"]})
    rows = sorted(rows, key=lambda row: (int(row.get("stage", -1)), row.get("stage_name", "")))
    registry["rows"] = rows
    registry["passed"] = summary["passed"]
    registry["metrics"] = {
        **(registry.get("metrics") or {}),
        "latest_stage": STAGE,
        "latest_stage_name": NAME,
        "latest_stage_next_best_step": summary["next_best_step"],
        "max_stage": max(STAGE, int((registry.get("metrics") or {}).get("max_stage", 0))),
        "registry_rows": len(rows),
        "authority_counts": {key: 0 for key in AUTHORITY_CLOSED},
    }
    REGISTRY.write_text(json.dumps(registry, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(summary, indent=2, sort_keys=True))
    raise SystemExit(0 if summary["passed"] else 1)


if __name__ == "__main__":
    main()
