#!/usr/bin/env python3
"""Build parser-verified foundational Python examples from pinned Git snapshots."""

from __future__ import annotations

import argparse
import ast
import collections
import ctypes
import hashlib
import io
import json
import os
import re
import stat
import subprocess
import sys
import tarfile
import textwrap
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping
from urllib.parse import urlsplit, urlunsplit

warnings.filterwarnings("ignore", category=SyntaxWarning)

ROOT = Path(__file__).resolve().parents[1]
STAGE = "stage12687_source_backed_python_foundational_corpus"
DEFAULT_SOURCE_ROOT = Path("/arxiv/repositories")
DEFAULT_OUT = ROOT / "runs/local/artifacts" / STAGE
DEFAULT_SUMMARY = ROOT / "runs/summaries" / f"{STAGE}.json"
ACQUISITION_DATE = "2026-08-02"

MAX_REPOS = 601
MAX_FILES_PER_REPO = 120
MAX_ROWS = 20_000
MAX_ROWS_PER_FILE = 3
MAX_ROWS_PER_REPO = 150
MIN_FILE_BYTES = 200
MAX_FILE_BYTES = 100_000
MIN_TARGET_CHARS = 8
MAX_TARGET_CHARS = 512
CONTEXT_BYTES_EACH_SIDE = 700
MAX_INPUT_CHARS = 1_800
MASK = "<MASKED_SOURCE_SPAN>"

LICENSE_NAMES = ("LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING", "COPYING.md", "NOTICE")
SUPPORTED_LICENSES = frozenset({"Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "MIT"})
EXCLUDED_PARTS = frozenset({
    ".git", ".hg", ".svn", ".tox", ".venv", "__pycache__", "build", "dist",
    "generated", "node_modules", "site-packages", "third_party", "vendor", "vendors",
})
EXCLUDED_SUFFIXES = (".min.py", "_pb2.py", "_pb2_grpc.py", ".generated.py")
REVISION_RE = re.compile(r"[0-9a-f]{40,64}")
SAFE_PATH_RE = re.compile(r"^[^\x00-\x1f<>]+$")
AI_GENERATED_MARKERS = (
    "generated by chatgpt",
    "generated by claude",
    "generated by copilot",
    "generated by a language model",
    "ai-generated",
    "ai generated",
)
SECRET_PATTERNS = (
    re.compile(rb"-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----"),
    re.compile(rb"(?:AKIA|ASIA)[0-9A-Z]{16}"),
    re.compile(rb"gh[pousr]_[A-Za-z0-9]{20,}"),
    re.compile(rb"github_pat_[A-Za-z0-9_]{20,}"),
    re.compile(rb"sk-(?:proj-)?[A-Za-z0-9_-]{20,}"),
    re.compile(rb"npm_[A-Za-z0-9]{20,}"),
    re.compile(rb"xox[baprs]-[A-Za-z0-9-]{10,}"),
    re.compile(rb"eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}"),
)
NODE_TYPES = (
    ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Assign, ast.AnnAssign,
    ast.AugAssign, ast.Return, ast.Assert, ast.Import, ast.ImportFrom, ast.If,
    ast.For, ast.AsyncFor, ast.While, ast.With, ast.AsyncWith, ast.Try, ast.Raise,
    ast.Match,
)
AUTHORITY = {
    "implementation_ready": False,
    "level_3_materialized": False,
    "model_execution_authorized": False,
    "replay_trustworthy": False,
    "sealed_eval_admitted": False,
    "strict_eval_admitted": False,
    "training_admitted": False,
    "training_allowed": False,
    "training_run_allowed": False,
}


class Stage12687Error(RuntimeError):
    pass


@dataclass(frozen=True)
class Blob:
    oid: str
    size: int
    path: str


@dataclass(frozen=True)
class ArtifactIdentity:
    device: int
    inode: int
    size: int
    sha256: str


@dataclass(frozen=True)
class PreparedRelease:
    rows: list[dict[str, Any]]
    proofs: list[dict[str, Any]]
    catalog: list[dict[str, Any]]
    public_payloads: dict[str, bytes]
    summary: dict[str, Any]


@dataclass
class RepoSnapshot:
    local_path: Path
    repo_key: str
    origin_url: str
    revision: str
    license_path: str
    license_oid: str
    license_id: str
    python_blobs: list[Blob]
    license_sha256: str = ""
    component_blobs: tuple[tuple[str, int], ...] = ()
    lineage_keys: tuple[str, ...] = ()
    component_key: str = ""
    split: str = ""


class UnionFind:
    def __init__(self, keys: Iterable[str]) -> None:
        self.parent = {key: key for key in keys}

    def find(self, key: str) -> str:
        root = key
        while self.parent[root] != root:
            root = self.parent[root]
        while self.parent[key] != key:
            key, self.parent[key] = self.parent[key], root
        return root

    def union(self, left: str, right: str) -> None:
        left, right = self.find(left), self.find(right)
        if left != right:
            keep, merge = sorted((left, right))
            self.parent[merge] = keep


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def stable(value: Any) -> str:
    payload = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return sha256_bytes(payload.encode("ascii"))


def git(repo: Path, *args: str, timeout: int = 60) -> bytes:
    env = dict(os.environ)
    env.update({"GIT_CONFIG_NOSYSTEM": "1", "GIT_OPTIONAL_LOCKS": "0", "LC_ALL": "C"})
    command = ["git", "-c", "core.quotepath=false", "-C", str(repo), *args]
    try:
        result = subprocess.run(
            command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            env=env, timeout=timeout,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise Stage12687Error(f"git_failed:{repo.name}:{args[0] if args else 'unknown'}") from exc
    return result.stdout


def sanitize_origin(raw: str) -> str:
    value = raw.strip()
    if not value or "\x00" in value or "\n" in value:
        return ""
    if value.startswith("git@") and ":" in value:
        host, path = value[4:].split(":", 1)
        path = path.split("?", 1)[0].split("#", 1)[0]
        return f"ssh://git@{host}/{path}" if host and path else ""
    parsed = urlsplit(value)
    if parsed.scheme not in {"https", "http", "ssh", "git"} or not parsed.hostname:
        return ""
    host = parsed.hostname + (f":{parsed.port}" if parsed.port else "")
    return urlunsplit((parsed.scheme, host, parsed.path, "", ""))


def parse_ls_tree(data: bytes) -> list[Blob]:
    blobs: list[Blob] = []
    for record in data.split(b"\0"):
        if not record:
            continue
        try:
            header, raw_path = record.split(b"\t", 1)
            _mode, object_type, oid, raw_size = header.decode("ascii").split()
            path, size = raw_path.decode("utf-8"), int(raw_size)
        except (UnicodeDecodeError, ValueError) as exc:
            raise Stage12687Error("malformed_ls_tree_record") from exc
        if object_type == "blob":
            blobs.append(Blob(oid=oid, size=size, path=path))
    return blobs


def path_allowed(path: str) -> bool:
    if not SAFE_PATH_RE.fullmatch(path) or path.startswith("/") or "\\" in path:
        return False
    parts = Path(path).parts
    if {part.lower() for part in parts}.intersection(EXCLUDED_PARTS):
        return False
    lower = path.lower()
    if not lower.endswith(".py") or lower.endswith(EXCLUDED_SUFFIXES):
        return False
    return not any(token in lower for token in ("/fixtures/", "/snapshots/", "/migrations/", "/_vendor/"))


def detect_license(text: str) -> str:
    normalized = " ".join(text.lower().split())
    if "apache license" in normalized and "version 2.0" in normalized:
        return "Apache-2.0"
    if "permission is hereby granted, free of charge" in normalized and "mit license" in normalized:
        return "MIT"
    if "isc license" in normalized or (
        "permission to use, copy, modify" in normalized and "the software is provided as is" in normalized
    ):
        return "ISC"
    if "redistribution and use in source and binary forms" in normalized:
        return "BSD-3-Clause" if "neither the name" in normalized else "BSD-2-Clause"
    return "unknown"


def verify_blob_oid(oid: str, data: bytes) -> bool:
    framed = f"blob {len(data)}\0".encode("ascii") + data
    if len(oid) == 40:
        return hashlib.sha1(framed).hexdigest() == oid
    if len(oid) == 64:
        return hashlib.sha256(framed).hexdigest() == oid
    return False


def cat_blobs(repo: Path, blobs: list[Blob]) -> dict[str, bytes]:
    if not blobs:
        return {}
    env = dict(os.environ)
    env.update({"GIT_CONFIG_NOSYSTEM": "1", "GIT_OPTIONAL_LOCKS": "0", "LC_ALL": "C"})
    command = ["git", "-C", str(repo), "cat-file", "--batch"]
    try:
        process = subprocess.Popen(command, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env)
    except OSError as exc:
        raise Stage12687Error(f"git_cat_file_failed:{repo.name}") from exc
    try:
        output, error = process.communicate(
            b"".join(blob.oid.encode("ascii") + b"\n" for blob in blobs), timeout=120
        )
    except subprocess.TimeoutExpired as exc:
        process.kill()
        process.communicate()
        raise Stage12687Error(f"git_cat_file_timeout:{repo.name}") from exc
    if process.returncode != 0 or error:
        raise Stage12687Error(f"git_cat_file_failed:{repo.name}")
    cursor = 0
    result: dict[str, bytes] = {}
    for blob in blobs:
        try:
            header_end = output.index(b"\n", cursor)
            returned_oid, object_type, raw_size = output[cursor:header_end].decode("ascii").split()
            size = int(raw_size)
        except (ValueError, UnicodeDecodeError) as exc:
            raise Stage12687Error(f"git_cat_file_header_invalid:{repo.name}") from exc
        start, end = header_end + 1, header_end + 1 + size
        data = output[start:end]
        if output[end:end + 1] != b"\n":
            raise Stage12687Error(f"git_cat_file_boundary_invalid:{repo.name}")
        if returned_oid != blob.oid or object_type != "blob" or size != blob.size or not verify_blob_oid(blob.oid, data):
            raise Stage12687Error(f"git_blob_identity_mismatch:{repo.name}:{blob.path}")
        result[blob.path] = data
        cursor = end + 1
    if cursor != len(output):
        raise Stage12687Error(f"git_cat_file_trailing_output:{repo.name}")
    return result


def contains_high_confidence_secret(data: bytes) -> bool:
    return any(pattern.search(data) for pattern in SECRET_PATTERNS)


def generated_content(data: bytes) -> bool:
    text = data.decode("utf-8", errors="ignore").lower()
    head = text[:4096]
    header_generated = any(marker in head for marker in (
        "automatically generated", "auto-generated", "code generated",
        "generated file", "generated by", "was generated", "do not edit", "@generated",
    ))
    return header_generated or any(marker in text for marker in AI_GENERATED_MARKERS)


def archive_blobs(repo: Path, revision: str, paths: list[str]) -> dict[str, bytes]:
    if not paths:
        return {}
    archive = git(repo, "archive", "--format=tar", revision, "--", *paths, timeout=120)
    result: dict[str, bytes] = {}
    try:
        with tarfile.open(fileobj=io.BytesIO(archive), mode="r:") as stream:
            for member in stream:
                if member.isfile() and member.name in paths:
                    handle = stream.extractfile(member)
                    if handle is not None:
                        result[member.name] = handle.read()
    except tarfile.TarError as exc:
        raise Stage12687Error(f"invalid_git_archive:{repo.name}") from exc
    return result


def discover_repositories(source_root: Path, max_repos: int) -> tuple[list[RepoSnapshot], collections.Counter[str]]:
    counters: collections.Counter[str] = collections.Counter()
    snapshots: list[RepoSnapshot] = []
    for repo in sorted((path for path in source_root.iterdir() if path.is_dir()), key=lambda path: path.name):
        if len(snapshots) >= max_repos:
            break
        counters["repository_directories_seen"] += 1
        if not (repo / ".git").exists():
            counters["without_git"] += 1
            continue
        try:
            revision = git(repo, "rev-parse", "--verify", "HEAD").decode("ascii").strip().lower()
            origin = sanitize_origin(git(repo, "config", "--get", "remote.origin.url").decode("utf-8"))
            entries = parse_ls_tree(git(repo, "ls-tree", "-r", "-l", "-z", revision))
            tree_oid = git(repo, "rev-parse", revision + "^{tree}").decode("ascii").strip().lower()
            root_commits = git(repo, "rev-list", "--max-parents=0", revision).decode("ascii").splitlines()
            remote_lines = git(repo, "remote", "-v").decode("utf-8").splitlines()
        except (Stage12687Error, UnicodeDecodeError):
            counters["git_metadata_failure"] += 1
            continue
        if not REVISION_RE.fullmatch(revision) or not origin:
            counters["unpinned_or_origin_missing"] += 1
            continue
        roots = {entry.path.lower(): entry for entry in entries if "/" not in entry.path}
        license_blob = next((roots[name.lower()] for name in LICENSE_NAMES if name.lower() in roots), None)
        if license_blob is None or license_blob.size > 256_000:
            counters["root_license_missing"] += 1
            continue
        license_data = cat_blobs(repo, [license_blob]).get(license_blob.path, b"")
        license_id = detect_license(license_data.decode("utf-8", errors="ignore"))
        if license_id not in SUPPORTED_LICENSES:
            counters["unsupported_or_unknown_license"] += 1
            continue
        all_candidates = [
            entry for entry in entries
            if MIN_FILE_BYTES <= entry.size <= MAX_FILE_BYTES and path_allowed(entry.path)
        ]
        candidates = list(all_candidates)
        candidates.sort(key=lambda entry: (stable([origin, revision, entry.path]), entry.path))
        candidates = candidates[:MAX_FILES_PER_REPO]
        if not candidates:
            counters["without_python_candidates"] += 1
            continue
        snapshots.append(RepoSnapshot(
            local_path=repo,
            repo_key=stable([origin, revision]),
            origin_url=origin,
            revision=revision,
            license_path=license_blob.path,
            license_oid=license_blob.oid,
            license_id=license_id,
            python_blobs=candidates,
            license_sha256=sha256_bytes(license_data),
            component_blobs=tuple(sorted((entry.oid, entry.size) for entry in all_candidates)),
            lineage_keys=tuple(sorted({
                *(f"root:{commit}" for commit in root_commits if REVISION_RE.fullmatch(commit)),
                f"tree:{tree_oid}",
                *(f"remote:{url}" for line in remote_lines for url in [sanitize_origin(line.split()[1] if len(line.split()) >= 2 else "")] if url),
            })),
        ))
        counters["repositories_accepted"] += 1
        counters["python_blobs_selected"] += len(candidates)
    return snapshots, counters


def assign_components(snapshots: list[RepoSnapshot]) -> None:
    union = UnionFind(snapshot.repo_key for snapshot in snapshots)
    owners: dict[tuple[str, int], str] = {}
    for snapshot in snapshots:
        for key in snapshot.component_blobs:
            if key in owners:
                union.union(snapshot.repo_key, owners[key])
            else:
                owners[key] = snapshot.repo_key
    lineage_owners: dict[str, str] = {}
    for snapshot in snapshots:
        for key in snapshot.lineage_keys:
            if key in lineage_owners:
                union.union(snapshot.repo_key, lineage_owners[key])
            else:
                lineage_owners[key] = snapshot.repo_key
    members: dict[str, list[str]] = collections.defaultdict(list)
    for snapshot in snapshots:
        members[union.find(snapshot.repo_key)].append(snapshot.repo_key)
    component_for = {
        repo_key: stable(sorted(repo_keys))
        for repo_keys in members.values()
        for repo_key in repo_keys
    }
    for snapshot in snapshots:
        snapshot.component_key = component_for[snapshot.repo_key]
        bucket = int(snapshot.component_key[:8], 16) % 20
        snapshot.split = "train" if bucket < 16 else "eval" if bucket < 18 else "strict_eval"


def byte_position(lines: list[bytes], line: int, column: int) -> int:
    if line < 1 or line > len(lines):
        raise Stage12687Error("ast_line_out_of_range")
    return sum(len(item) for item in lines[: line - 1]) + column


def adjust_utf8_start(data: bytes, offset: int) -> int:
    offset = max(0, min(offset, len(data)))
    while offset < len(data) and offset > 0 and data[offset] & 0xC0 == 0x80:
        offset += 1
    return min(offset, len(data))


PLACEHOLDER_TARGET_RE = re.compile(r"\b(?:TODO|FIXME|TBD)\b", re.IGNORECASE)


def is_not_implemented_raise(node: ast.stmt) -> bool:
    if not isinstance(node, ast.Raise) or node.exc is None:
        return False
    expression = node.exc.func if isinstance(node.exc, ast.Call) else node.exc
    return isinstance(expression, ast.Name) and expression.id == "NotImplementedError"


def target_is_stub_or_placeholder(target: str) -> bool:
    if PLACEHOLDER_TARGET_RE.search(target):
        return True
    try:
        body = ast.parse(textwrap.dedent(target)).body
    except (SyntaxError, ValueError):
        return False
    if len(body) != 1:
        return False
    node = body[0]
    if is_not_implemented_raise(node):
        return True
    if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
        return False
    statements = list(node.body)
    if statements and isinstance(statements[0], ast.Expr) and isinstance(statements[0].value, ast.Constant) and isinstance(statements[0].value.value, str):
        statements = statements[1:]
    return bool(statements) and all(
        isinstance(statement, ast.Pass)
        or (
            isinstance(statement, ast.Expr)
            and isinstance(statement.value, ast.Constant)
            and statement.value.value is Ellipsis
        )
        or is_not_implemented_raise(statement)
        for statement in statements
    )


def candidate_spans(data: bytes, tree: ast.AST, repo_key: str, path: str) -> list[tuple[int, int, str]]:
    lines = data.splitlines(keepends=True)
    candidates: list[tuple[int, int, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, NODE_TYPES) or not hasattr(node, "end_lineno"):
            continue
        try:
            start = byte_position(lines, int(node.lineno), int(node.col_offset))
            end = byte_position(lines, int(node.end_lineno), int(node.end_col_offset))
            target = data[start:end].decode("utf-8")
        except (AttributeError, Stage12687Error, UnicodeDecodeError):
            continue
        if end <= start or not (MIN_TARGET_CHARS <= len(target) <= MAX_TARGET_CHARS):
            continue
        if MASK in target or not target.strip() or target_is_stub_or_placeholder(target):
            continue
        candidates.append((start, end, type(node).__name__))
    candidates.sort(key=lambda item: (stable([repo_key, path, item[0], item[1], item[2]]), item))
    selected: list[tuple[int, int, str]] = []
    for candidate in candidates:
        if any(not (candidate[1] <= prior[0] or candidate[0] >= prior[1]) for prior in selected):
            continue
        selected.append(candidate)
        if len(selected) >= MAX_ROWS_PER_FILE:
            break
    return selected


def normalize_visible_code(value: str) -> str:
    return "".join(value.split())


def build_row(
    snapshot: RepoSnapshot,
    blob: Blob,
    data: bytes,
    tree: ast.AST,
    span: tuple[int, int, str],
) -> tuple[dict[str, Any], dict[str, Any]] | None:
    start, end, node_type = span
    left = adjust_utf8_start(data, start - CONTEXT_BYTES_EACH_SIDE)
    right = adjust_utf8_start(data, end + CONTEXT_BYTES_EACH_SIDE)
    try:
        before = data[left:start].decode("utf-8")
        target = data[start:end].decode("utf-8")
        after = data[end:right].decode("utf-8")
    except UnicodeDecodeError:
        return None
    source_window = before + target + after
    input_text = (
        f"repository_relative_path: {blob.path}\n"
        f"<PYTHON_SOURCE>\n{before}{MASK}{after}\n</PYTHON_SOURCE>"
    )
    if (
        len(input_text) > MAX_INPUT_CHARS
        or input_text.count(MASK) != 1
        or target in input_text
        or normalize_visible_code(target) in normalize_visible_code(input_text)
    ):
        return None
    expected = (
        f"repository_relative_path: {blob.path}\n"
        f"<PYTHON_SOURCE>\n{source_window}\n</PYTHON_SOURCE>"
    )
    if input_text.replace(MASK, target, 1) != expected:
        raise Stage12687Error("source_reconstruction_failure")
    reconstructed = data[:start] + target.encode("utf-8") + data[end:]
    if reconstructed != data or ast.dump(ast.parse(reconstructed.decode("utf-8"))) != ast.dump(tree):
        raise Stage12687Error("ast_roundtrip_failure")
    file_sha = sha256_bytes(data)
    window_sha = sha256_bytes(source_window.encode("utf-8"))
    target_sha = sha256_bytes(target.encode("utf-8"))
    row_id = "stage12687_" + stable([snapshot.repo_key, blob.path, start, end, target_sha])[:24]
    row = {
        "row_id": row_id,
        "split": snapshot.split,
        "language_family": "python",
        "objective_family": "python_parser_source_span_infilling",
        "input_text": input_text,
        "target": {"decoder_text": target},
        "loss_mask": {"decoder_ce": True},
        "source_provenance": {
            "source_stage": STAGE,
            "origin_url": snapshot.origin_url,
            "revision": snapshot.revision,
            "repository_key_sha256": snapshot.repo_key,
            "content_component_sha256": snapshot.component_key,
            "repository_relative_path": blob.path,
            "git_blob_oid": blob.oid,
            "source_file_sha256": file_sha,
            "license_id": snapshot.license_id,
            "license_file": snapshot.license_path,
            "license_git_blob_oid": snapshot.license_oid,
            "license_file_sha256": snapshot.license_sha256,
            "ast_node_type": node_type,
            "span_start_byte": start,
            "span_end_byte": end,
            "source_window_sha256": window_sha,
            "target_sha256": target_sha,
            "python_version": sys.version.split()[0],
            "ast_contract": "cpython_ast_exact_reinsert_v1",
            "acquisition_date": ACQUISITION_DATE,
            "license_review_required": True,
        },
        "authority": dict(AUTHORITY),
    }
    model_example_sha = stable([input_text, target])
    semantic_example_sha = stable([" ".join(input_text.splitlines()[1:]).split(), " ".join(target.split())])
    proof = {
        "row_id": row_id,
        "row_sha256": stable(row),
        "model_example_sha256": model_example_sha,
        "semantic_example_sha256": semantic_example_sha,
        "split": snapshot.split,
        "repository_key_sha256": snapshot.repo_key,
        "content_component_sha256": snapshot.component_key,
        "revision": snapshot.revision,
        "repository_relative_path_sha256": sha256_bytes(blob.path.encode("utf-8")),
        "git_blob_oid": blob.oid,
        "source_file_sha256": file_sha,
        "source_window_sha256": window_sha,
        "target_sha256": target_sha,
        "span_start_byte": start,
        "span_end_byte": end,
        "ast_node_type": node_type,
        "byte_exact_reinsertion_verified": True,
        "ast_roundtrip_verified": True,
        "training_admitted": False,
        "strict_eval_admitted": False,
        "sealed_eval_admitted": False,
    }
    return row, proof


def fsync_dir(path: Path) -> None:
    fd = os.open(str(path), os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def open_directory_nofollow(path: Path) -> int:
    absolute = path.absolute()
    flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_NOFOLLOW", 0)
    fd = os.open("/", flags)
    try:
        for part in absolute.parts[1:]:
            next_fd = os.open(part, flags, dir_fd=fd)
            os.close(fd)
            fd = next_fd
        return fd
    except BaseException:
        os.close(fd)
        raise


def secure_atomic_write(path: Path, data: bytes, *, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = f".{path.name}.tmp.{os.getpid()}.{sha256_bytes(data)[:12]}"
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
    parent_fd = open_directory_nofollow(path.parent)
    try:
        fd = os.open(temporary, flags, mode, dir_fd=parent_fd)
        try:
            view = memoryview(data)
            while view:
                written = os.write(fd, view)
                view = view[written:]
            os.fchmod(fd, mode)
            os.fsync(fd)
        finally:
            os.close(fd)
        os.replace(temporary, path.name, src_dir_fd=parent_fd, dst_dir_fd=parent_fd)
        os.fsync(parent_fd)
    finally:
        os.close(parent_fd)


def sha256_open_fd(fd: int) -> str:
    digest = hashlib.sha256()
    os.lseek(fd, 0, os.SEEK_SET)
    while True:
        chunk = os.read(fd, 1024 * 1024)
        if not chunk:
            break
        digest.update(chunk)
    os.lseek(fd, 0, os.SEEK_SET)
    return digest.hexdigest()


def write_file_at(
    directory_fd: int, name: str, data: bytes, *, mode: int
) -> ArtifactIdentity:
    if not name or "/" in name or "\\" in name or name in {".", ".."}:
        raise Stage12687Error("unsafe_publication_filename")
    flags = os.O_RDWR | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
    fd = os.open(name, flags, mode, dir_fd=directory_fd)
    try:
        opened = os.fstat(fd)
        if not stat.S_ISREG(opened.st_mode):
            raise Stage12687Error("publication_leaf_not_regular")
        view = memoryview(data)
        while view:
            written = os.write(fd, view)
            if written <= 0:
                raise Stage12687Error("publication_short_write")
            view = view[written:]
        os.fchmod(fd, mode)
        os.fsync(fd)
        finalized = os.fstat(fd)
        digest = sha256_open_fd(fd)
        if finalized.st_size != len(data):
            raise Stage12687Error("publication_size_mismatch")
        return ArtifactIdentity(
            device=finalized.st_dev,
            inode=finalized.st_ino,
            size=finalized.st_size,
            sha256=digest,
        )
    finally:
        os.close(fd)


def rename_noreplace(parent_fd: int, source_name: str, destination_name: str) -> None:
    renameat2 = getattr(ctypes.CDLL(None, use_errno=True), "renameat2", None)
    if renameat2 is None:
        raise Stage12687Error("renameat2_noreplace_unavailable")
    renameat2.argtypes = [
        ctypes.c_int, ctypes.c_char_p, ctypes.c_int, ctypes.c_char_p, ctypes.c_uint,
    ]
    renameat2.restype = ctypes.c_int
    if renameat2(
        parent_fd, source_name.encode("utf-8"),
        parent_fd, destination_name.encode("utf-8"),
        1,
    ) != 0:
        error_number = ctypes.get_errno()
        if error_number == 17:
            raise Stage12687Error(f"immutable_generation_exists:{destination_name}")
        raise OSError(error_number, os.strerror(error_number), destination_name)


def revalidate_pending_identity(
    private_fd: int, pending_name: str, pending_fd: int, expected: tuple[int, int]
) -> os.stat_result:
    held = os.fstat(pending_fd)
    try:
        named = os.stat(pending_name, dir_fd=private_fd, follow_symlinks=False)
    except OSError as exc:
        raise Stage12687Error("pending_generation_identity_unavailable") from exc
    if (
        not stat.S_ISDIR(held.st_mode)
        or not stat.S_ISDIR(named.st_mode)
        or (held.st_dev, held.st_ino) != expected
        or (named.st_dev, named.st_ino) != expected
    ):
        raise Stage12687Error("pending_generation_inode_mismatch")
    return named


def verify_published_generation(
    private_fd: int,
    generation_name: str,
    expected_directory: tuple[int, int],
    expected_artifacts: Mapping[str, ArtifactIdentity],
) -> None:
    flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        named = os.stat(generation_name, dir_fd=private_fd, follow_symlinks=False)
        generation_fd = os.open(generation_name, flags, dir_fd=private_fd)
    except OSError as exc:
        raise Stage12687Error("published_generation_unavailable") from exc
    try:
        opened = os.fstat(generation_fd)
        if (
            not stat.S_ISDIR(named.st_mode)
            or not stat.S_ISDIR(opened.st_mode)
            or (named.st_dev, named.st_ino) != expected_directory
            or (opened.st_dev, opened.st_ino) != expected_directory
        ):
            raise Stage12687Error("published_generation_inode_mismatch")
        artifact_flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
        for name, expected in expected_artifacts.items():
            artifact_fd = os.open(name, artifact_flags, dir_fd=generation_fd)
            try:
                artifact = os.fstat(artifact_fd)
                if (
                    not stat.S_ISREG(artifact.st_mode)
                    or (artifact.st_dev, artifact.st_ino) != (expected.device, expected.inode)
                    or artifact.st_size != expected.size
                    or sha256_open_fd(artifact_fd) != expected.sha256
                ):
                    raise Stage12687Error(
                        f"published_generation_artifact_identity_mismatch:{name}"
                    )
            finally:
                os.close(artifact_fd)
    finally:
        os.close(generation_fd)


def publish_generation(
    output_dir: Path,
    generation_id: str,
    artifact_payloads: Mapping[str, bytes],
    summary: Mapping[str, Any],
) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
    output_fd = open_directory_nofollow(output_dir)
    private_fd: int | None = None
    pending_fd: int | None = None
    private_name = "private"
    pending_name = f".pending-{generation_id}-{os.getpid()}"
    generation_name = generation_id
    directory_flags = (
        os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_NOFOLLOW", 0)
    )
    summary_payload = (
        json.dumps(summary, indent=2, sort_keys=True, ensure_ascii=True) + "\n"
    ).encode("ascii")
    try:
        try:
            os.mkdir(private_name, 0o700, dir_fd=output_fd)
            os.fsync(output_fd)
        except FileExistsError:
            pass
        private_named = os.stat(private_name, dir_fd=output_fd, follow_symlinks=False)
        private_fd = os.open(private_name, directory_flags, dir_fd=output_fd)
        private_opened = os.fstat(private_fd)
        if (
            not stat.S_ISDIR(private_named.st_mode)
            or (private_named.st_dev, private_named.st_ino)
            != (private_opened.st_dev, private_opened.st_ino)
        ):
            raise Stage12687Error("private_root_inode_mismatch")
        os.fchmod(private_fd, 0o700)
        try:
            os.stat(generation_name, dir_fd=private_fd, follow_symlinks=False)
        except FileNotFoundError:
            pass
        else:
            raise Stage12687Error(f"immutable_generation_exists:{generation_id}")
        os.mkdir(pending_name, 0o700, dir_fd=private_fd)
        pending_fd = os.open(pending_name, directory_flags, dir_fd=private_fd)
        pending_stat = os.fstat(pending_fd)
        pending_identity = (pending_stat.st_dev, pending_stat.st_ino)
        expected_artifacts = {
            name: write_file_at(pending_fd, name, payload, mode=0o400)
            for name, payload in artifact_payloads.items()
        }
        expected_artifacts["summary.json"] = write_file_at(
            pending_fd, "summary.json", summary_payload, mode=0o400
        )
        os.fchmod(pending_fd, 0o500)
        os.fsync(pending_fd)
        revalidate_pending_identity(
            private_fd, pending_name, pending_fd, pending_identity
        )
        rename_noreplace(private_fd, pending_name, generation_name)
        verify_published_generation(
            private_fd, generation_name, pending_identity, expected_artifacts
        )
        os.fsync(private_fd)
    finally:
        if pending_fd is not None:
            os.close(pending_fd)
        if private_fd is not None:
            os.close(private_fd)
        os.close(output_fd)
    return output_dir / private_name / generation_name


def write_json_atomic(path: Path, value: Any) -> None:
    data = (json.dumps(value, indent=2, sort_keys=True, ensure_ascii=True) + "\n").encode("ascii")
    secure_atomic_write(path, data, mode=0o644)


def write_jsonl_atomic(path: Path, rows: Iterable[Mapping[str, Any]]) -> None:
    data = b"".join(
        json.dumps(row, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("ascii") + b"\n"
        for row in rows
    )
    secure_atomic_write(path, data, mode=0o600)


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def finalized_cross_split_overlap(
    proofs: list[dict[str, Any]], field: str
) -> dict[str, Any]:
    owners: dict[str, set[str]] = collections.defaultdict(set)
    for proof in proofs:
        value = proof.get(field)
        if value:
            owners[str(value)].add(proof["split"])
    overlapping = sorted(value for value, splits in owners.items() if len(splits) > 1)
    return {
        "field": field,
        "overlap_count": len(overlapping),
        "overlap_value_commitment_sha256": stable(overlapping),
        "computed_from_finalized_rows": True,
    }


def prepare_release(
    source_root: Path,
    *,
    max_repos: int,
    max_rows: int,
) -> PreparedRelease:
    if max_rows < 10 or max_rows % 10 != 0:
        raise Stage12687Error("invalid_max_rows_exact_80_10_10_required")
    if not source_root.is_dir():
        raise Stage12687Error(f"source_root_missing:{source_root}")
    snapshots, counters = discover_repositories(source_root, max_repos)
    if not snapshots:
        raise Stage12687Error("no_eligible_repositories")
    assign_components(snapshots)
    split_caps = {
        "train": max_rows * 8 // 10,
        "eval": max_rows // 10,
        "strict_eval": max_rows - max_rows * 8 // 10 - max_rows // 10,
    }
    rows: list[dict[str, Any]] = []
    proofs: list[dict[str, Any]] = []
    source_catalog: list[dict[str, Any]] = []
    split_counts: collections.Counter[str] = collections.Counter()
    row_ids: set[str] = set()
    row_hashes: set[str] = set()
    model_example_hashes: set[str] = set()
    semantic_example_hashes: set[str] = set()
    window_splits: dict[str, str] = {}
    file_splits: dict[str, str] = {}
    repo_row_counts: collections.Counter[str] = collections.Counter()

    for snapshot in sorted(snapshots, key=lambda item: (item.component_key, item.repo_key)):
        source_catalog.append({
            "repository_key_sha256": snapshot.repo_key,
            "origin_url": snapshot.origin_url,
            "revision": snapshot.revision,
            "content_component_sha256": snapshot.component_key,
            "split": snapshot.split,
            "license_id": snapshot.license_id,
            "license_file": snapshot.license_path,
            "license_git_blob_oid": snapshot.license_oid,
            "license_file_sha256": snapshot.license_sha256,
            "license_review_required": True,
            "selected_python_blob_count": len(snapshot.python_blobs),
        })
        if split_counts[snapshot.split] >= split_caps[snapshot.split]:
            continue
        try:
            contents = cat_blobs(snapshot.local_path, snapshot.python_blobs)
        except Stage12687Error:
            counters["archive_failure"] += 1
            continue
        for blob in snapshot.python_blobs:
            if split_counts[snapshot.split] >= split_caps[snapshot.split] or repo_row_counts[snapshot.repo_key] >= MAX_ROWS_PER_REPO:
                break
            data = contents.get(blob.path)
            if data is None or len(data) != blob.size or b"\x00" in data or generated_content(data) or contains_high_confidence_secret(data):
                counters["missing_size_mismatch_binary_generated_or_secret"] += 1
                continue
            try:
                tree = ast.parse(data.decode("utf-8"), filename=blob.path)
            except (UnicodeDecodeError, SyntaxError, ValueError):
                counters["parse_rejected"] += 1
                continue
            file_sha = sha256_bytes(data)
            prior_file_split = file_splits.setdefault(file_sha, snapshot.split)
            if prior_file_split != snapshot.split:
                raise Stage12687Error("cross_split_file_digest")
            counters["python_files_parsed"] += 1
            for span in candidate_spans(data, tree, snapshot.repo_key, blob.path):
                if split_counts[snapshot.split] >= split_caps[snapshot.split] or repo_row_counts[snapshot.repo_key] >= MAX_ROWS_PER_REPO:
                    break
                built = build_row(snapshot, blob, data, tree, span)
                if built is None:
                    counters["row_window_rejected"] += 1
                    continue
                row, proof = built
                window_sha = proof["source_window_sha256"]
                if window_sha in window_splits:
                    counters["duplicate_source_window_quarantined"] += 1
                    continue
                window_splits[window_sha] = snapshot.split
                if row["row_id"] in row_ids or proof["row_sha256"] in row_hashes:
                    counters["duplicate_row_quarantined"] += 1
                    continue
                if proof["model_example_sha256"] in model_example_hashes or proof["semantic_example_sha256"] in semantic_example_hashes:
                    counters["duplicate_model_example_quarantined"] += 1
                    continue
                row_ids.add(row["row_id"])
                row_hashes.add(proof["row_sha256"])
                model_example_hashes.add(proof["model_example_sha256"])
                semantic_example_hashes.add(proof["semantic_example_sha256"])
                rows.append(row)
                proofs.append(proof)
                split_counts[snapshot.split] += 1
                repo_row_counts[snapshot.repo_key] += 1
                counters["rows_materialized"] += 1
        if len(rows) >= max_rows:
            break

    if any(split_counts[split] != split_caps[split] for split in ("train", "eval", "strict_eval")):
        raise Stage12687Error("requested_split_caps_unfilled")
    source_catalog = [{
        "repository_key_sha256": snapshot.repo_key,
        "origin_url": snapshot.origin_url,
        "revision": snapshot.revision,
        "content_component_sha256": snapshot.component_key,
        "split": snapshot.split,
        "license_id": snapshot.license_id,
        "license_file": snapshot.license_path,
        "license_git_blob_oid": snapshot.license_oid,
        "license_file_sha256": snapshot.license_sha256,
        "license_review_required": True,
        "selected_python_blob_count": len(snapshot.python_blobs),
        "eligible_python_blob_count": len(snapshot.component_blobs),
        "eligible_python_blob_set_sha256": stable(snapshot.component_blobs),
        "root_commit_git_oids": sorted(key[5:] for key in snapshot.lineage_keys if key.startswith("root:")),
        "tree_git_oids": sorted(key[5:] for key in snapshot.lineage_keys if key.startswith("tree:")),
        "remote_lineage_url_sha256s": sorted(
            sha256_bytes(key[7:].encode("utf-8"))
            for key in snapshot.lineage_keys
            if key.startswith("remote:")
        ),
        "lineage_key_sha256s": [sha256_bytes(key.encode("utf-8")) for key in snapshot.lineage_keys],
    } for snapshot in snapshots]
    train_eval = [row for row in rows if row["split"] != "strict_eval"]
    strict = [row for row in rows if row["split"] == "strict_eval"]
    train_eval_proofs = [proof for proof in proofs if proof["split"] != "strict_eval"]
    strict_proofs = [proof for proof in proofs if proof["split"] == "strict_eval"]
    train_eval_catalog = [entry for entry in source_catalog if entry["split"] != "strict_eval"]
    strict_eval_commitment_sha256 = stable(sorted(proof["row_sha256"] for proof in strict_proofs))
    overlap_fields = {
        "repository": "repository_key_sha256",
        "component": "content_component_sha256",
        "file_digest": "source_file_sha256",
        "source_window": "source_window_sha256",
        "model_example": "model_example_sha256",
        "semantic_example": "semantic_example_sha256",
    }

    internal_overlap_metrics = {
        name: finalized_cross_split_overlap(proofs, field)
        for name, field in overlap_fields.items()
    }
    if any(metric["overlap_count"] for metric in internal_overlap_metrics.values()):
        raise Stage12687Error("finalized_cross_split_overlap_detected")
    public_overlap_metrics = {
        name: finalized_cross_split_overlap(train_eval_proofs, field)
        for name, field in overlap_fields.items()
    }
    public_repo_row_counts = collections.Counter(
        proof["repository_key_sha256"] for proof in train_eval_proofs
    )
    public_split_counts = collections.Counter(row["split"] for row in train_eval)
    artifact_schema_version = 4
    artifact_values = {
        "foundational_train_eval_manifest.jsonl": train_eval,
        "train_eval_source_provenance_ledger.jsonl": train_eval_proofs,
        "train_eval_source_catalog.jsonl": train_eval_catalog,
    }
    artifact_payloads = {
        name: b"".join(
            json.dumps(row, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("ascii") + b"\n"
            for row in values
        )
        for name, values in artifact_values.items()
    }
    artifact_identity_inputs = sorted(
        (name, len(artifact_values[name]), sha256_bytes(payload))
        for name, payload in artifact_payloads.items()
    )
    generation_id = stable([
        "stage12687_generation_v4_public_artifacts_and_strict_commitment",
        artifact_schema_version,
        artifact_identity_inputs,
        len(strict),
        strict_eval_commitment_sha256,
    ])[:24]
    artifact_contract = {
        name: {
            "relative_path": f"private/{generation_id}/{name}",
            "rows": len(artifact_values[name]),
            "sha256": sha256_bytes(payload),
        }
        for name, payload in artifact_payloads.items()
    }
    summary = {
        "stage": STAGE,
        "generation_id": generation_id,
        "generation_relative_path": f"private/{generation_id}",
        "artifact_schema_version": artifact_schema_version,
        "authoritative_summary_relative_path": f"private/{generation_id}/summary.json",
        "generation_and_authoritative_summary_transactional": True,
        "external_summary_mirrors_are_nonauthoritative": True,
        "decision": "SOURCE_BACKED_PYTHON_FOUNDATIONAL_CORPUS_MATERIALIZED_RELEASE_REVIEW_REQUIRED",
        "objective": "python_parser_source_span_infilling",
        "source_root_recorded_publicly": False,
        "repository_snapshots": len(train_eval_catalog),
        "content_components": len({
            entry["content_component_sha256"] for entry in train_eval_catalog
        }),
        "repositories_contributing_rows": len(public_repo_row_counts),
        "maximum_rows_from_one_repository": max(public_repo_row_counts.values(), default=0),
        "license_counts": dict(sorted(collections.Counter(
            entry["license_id"] for entry in train_eval_catalog
        ).items())),
        "materialized_model_row_count": len(train_eval),
        "reserved_unmaterialized_strict_row_count": len(strict),
        "strict_eval_commitment_sha256": strict_eval_commitment_sha256,
        "public_split_counts": dict(sorted(public_split_counts.items())),
        "stub_or_placeholder_target_rows": sum(
            target_is_stub_or_placeholder(row["target"]["decoder_text"]) for row in train_eval
        ),
        "byte_exact_reinsertion_verified_rows": len(train_eval),
        "ast_roundtrip_verified_rows": len(train_eval),
        "distinct_row_ids": len({row["row_id"] for row in train_eval}),
        "distinct_row_hashes": len({proof["row_sha256"] for proof in train_eval_proofs}),
        "distinct_model_example_hashes": len({
            proof["model_example_sha256"] for proof in train_eval_proofs
        }),
        "distinct_semantic_example_hashes": len({
            proof["semantic_example_sha256"] for proof in train_eval_proofs
        }),
        "source_catalog_rows": len(train_eval_catalog),
        "public_split_overlap_metrics": public_overlap_metrics,
        "train_eval_repository_overlap": public_overlap_metrics["repository"]["overlap_count"],
        "train_eval_component_overlap": public_overlap_metrics["component"]["overlap_count"],
        "train_eval_file_digest_overlap": public_overlap_metrics["file_digest"]["overlap_count"],
        "train_eval_source_window_overlap": public_overlap_metrics["source_window"]["overlap_count"],
        "artifact_contract": artifact_contract,
        "training_eligible_rows": 0,
        "release_blockers": [
            "independent_semantic_and_leakage_review_required",
            "license_and_training_permission_review_required",
            "dedicated_foundational_code_ce_trainer_mode_required",
            "tokenizer_bound_target_and_context_audit_required",
        ],
        "authority": dict(AUTHORITY),
    }
    return PreparedRelease(
        rows=rows,
        proofs=proofs,
        catalog=source_catalog,
        public_payloads=artifact_payloads,
        summary=summary,
    )


def build(
    source_root: Path,
    output_dir: Path,
    summary_path: Path,
    *,
    max_repos: int,
    max_rows: int,
) -> dict[str, Any]:
    prepared = prepare_release(source_root, max_repos=max_repos, max_rows=max_rows)
    summary = prepared.summary
    publish_generation(
        output_dir, summary["generation_id"], prepared.public_payloads, summary
    )
    write_json_atomic(summary_path, summary)
    write_json_atomic(output_dir / "summary.json", summary)
    return summary


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", type=Path, default=DEFAULT_SOURCE_ROOT)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--summary-path", type=Path, default=DEFAULT_SUMMARY)
    parser.add_argument("--max-repos", type=int, default=MAX_REPOS)
    parser.add_argument("--max-rows", type=int, default=MAX_ROWS)
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    if args.max_repos <= 0 or args.max_rows < 10 or args.max_rows % 10 != 0:
        raise SystemExit(
            "max-repos must be positive and max-rows must be at least 10 and divisible by 10"
        )
    print(json.dumps(build(
        args.source_root.resolve(),
        args.output_dir.resolve(),
        args.summary_path.resolve(),
        max_repos=args.max_repos,
        max_rows=args.max_rows,
    ), indent=2, sort_keys=True))
